// The six itineraries that were NOT chosen, plus the two tables that compare all seven.
//
// This is an archive: it is a record of how the decision was made, not a live document. Leave the
// dates, costs and verdicts as they were when Itinerary 1B was picked on 15 August 2026 — the
// comparison stops meaning anything if the losing options keep being revised. Plan changes belong
// in content/plan.mjs and content/history.mjs.
//
// The plan itself is deliberately absent from this array. build.mjs splices it back in wherever the
// archive needs all seven (the glance table, the cards, the wish-list matrix), badged and linked to
// index.html — a comparison with the winner missing cannot be read.

export const alternates = [
  // ══════════════════════════════════════════════════════════════ 1 ══
  {
    num: 1,
    slug: 'peak-momiji-classic',
    title: 'The Kyoto Classic',
    tagline: 'The seeds trip, with the longest Kyoto block of any option',
    dates: 'Sat Nov 7 → Sun Nov 22, 2026',
    length: '14 nights',
    route: ['Tokyo · 4n', 'Hakone · 2n', 'Kyoto · 8n'],
    routeNote: 'Open-jaw, returning from KIX — home three days before Colorado',
    cost: '$34,800',
    costBand: '$33–35k',
    temp: '45–65°F',
    tempStatus: 'good',
    bestFor: 'The most Kyoto time, Gora Kadan, both seed restaurants',
    transport: {
      mode: 'Rail',
      text: `This route never leaves the shinkansen spine — a car would sit in $70/day parking through peak-season gridlock. Green Car booked via the smartEX app; takkyubin the bags Tokyo→Kyoto past the Hakone stop; private transfers on arrival and departure days.`,
      ref: ['shinkansen-green-car', 'ana-the-room'],
    },
    hero: 'eikando',
    heroCard: ['gora-kadan', 'tofukuji', 'hirata-sword'],
    pitch: `Still the trip your seeds describe most literally — Gora Kadan, Kikunoi, Jugyuan, sword smithing, the deep kintsugi, kyudo — with a full eight nights in Kyoto — the longest run in any version. Trimming the workshops did two things: it took $4,000 off the number, and it opened four days that are now the best wildlife in the plan outside Hokkaido. Flying squirrels at Karuizawa on the Wednesday, the Nara deer on the holiday Monday, the Iwatayama macaques above Arashiyama, and an owl café on the first Tokyo afternoon.`,
    days: [
      { date: 'Sat 7', where: '✈', text: 'SFO→HND, ANA The Room', ref: ['ana-the-room'] },
      { date: 'Sun 8', where: 'Tokyo', text: 'Land, private transfer, gentle evening. <strong>Aman Tokyo</strong>.', ref: ['aman-tokyo'] },
      { date: 'Mon 9', where: 'Tokyo', text: 'Meiji Jingu and the Jingu Gaien ginkgo. <em>They gold up around 20 Nov, so this early expect green-to-yellow rather than the corridor of gold.</em> Afternoon: <strong>Akiba Fukurou</strong>, the owl café — reservation only, so book it now. <em>No dinner booking tonight: L\'Effervescence is closed Sundays and Mondays.</em>', ref: ['meiji-jingu', 'omotesando-ginkgo', 'akiba-fukurou'] },
      { date: 'Tue 10', where: 'Tokyo · Ome', text: '<strong>Hirata sword smithing</strong> — forge a small katana with the husband-and-wife smiths, engraved and shipped home. 150 min, ≈ $1,700/couple. The exact experience from the seeds. Back in town for <strong>L\'Effervescence</strong> — 3★, printed GF menu, ≈ $1,200/couple.', ref: ['hirata-sword', 'leffervescence'] },
      { date: 'Wed 11', where: 'Karuizawa', text: '<strong>Flying squirrels.</strong> Shinkansen out after lunch (1h10), then Picchio\'s <strong>musasabi watching tour</strong> — a nest camera, then the animal leaving the hole at dusk to glide. 16:00–17:30 in November; back in Tokyo by about 19:15. Better than 90% success. <em>Book early: the season closes 30 November.</em>', ref: ['picchio-musasabi', 'gran-class'] },
      { date: 'Thu 12', where: 'Hakone', text: 'Romancecar or private transfer. <strong>Gora Kadan</strong> — in-room gluten-free kaiseki, cypress onsen.', ref: ['gora-kadan'] },
      { date: 'Fri 13', where: 'Hakone', text: 'Open-Air Museum, Lake Ashi — foliage peaks here mid-November. Lunch at <strong>Itoh Dining by Nobu</strong> (teppanyaki, a GF-safe format). Second kaiseki at the ryokan.', ref: ['hakone-open-air-museum', 'lake-ashi', 'itoh-dining-nobu'] },
      { date: 'Sat 14', where: 'Kyoto', text: 'Green Car Odawara→Kyoto. Check in to <strong>Sowaka</strong> in Gion (or Hotel The Mitsui, +$1–3k/night). Evening Gion walk.', ref: ['sowaka', 'gion'] },
      { date: 'Sun 15', where: 'Kyoto', text: 'Early — 8am — Honen-in and the Philosopher\'s Path before the crowds. <strong>Kodaiji Jugyuan</strong> dinner (2★, from the seeds) — literally next door to Kodai-ji\'s night illumination.', ref: ['philosophers-path', 'kodaiji-jugyuan', 'kodaiji'] },
      { date: 'Mon 16', where: 'Nara', text: '<em>Public holiday — leave the city.</em> <strong>Nara</strong>: a thousand sika deer loose among the temples, Todai-ji\'s Great Buddha hall, and the stone lantern avenue at Kasuga Taisha. 45 minutes each way, and the best wildlife photography on the Kansai side. <em>Alternative if you would rather have tea country: Uji and Byodo-in.</em>', ref: ['nara-deer', 'byodo-in-uji'] },
      { date: 'Tue 17', where: 'Kyoto', text: '<strong>Traditional kintsugi with Mio Heki</strong> at a Higashiyama villa (120 min, ≈ $600/couple, real-gold option) — the one craft workshop you kept, and the deep version. Eikando illumination in the evening.', ref: ['heki-kintsugi', 'eikando'] },
      { date: 'Wed 18', where: 'Kyoto · Arashiyama', text: 'A full day west. <strong>Iwatayama monkey park</strong> at opening — 120 wild macaques on a hilltop with Kyoto spread out behind them — then the bamboo grove, Tenryu-ji\'s garden and the Hozugawa in colour, all before the afternoon crowds thicken.', ref: ['arashiyama-monkeys', 'arashiyama'] },
      { date: 'Thu 19', where: 'Kyoto', text: '<strong>Kikunoi Honten</strong> (3★, formal GF process — book Aug/Sep, ≈ $900–1,100/couple). Morning <strong>kyudo</strong> session (≈ $270/couple; confirm the studio location by email).', ref: ['kikunoi-honten', 'kyudo'] },
      { date: 'Fri 20', where: 'Kyoto · Ohara', text: 'Ohara at peak colour: <strong>Sanzen-in</strong> and its moss garden of jizo figures, forty minutes north and dramatically less crowded than the city. <strong>Rurikoin</strong> on the way back if you reserved it.', ref: ['sanzen-in-ohara', 'rurikoin'] },
      { date: 'Sat 21', where: 'Kyoto', text: 'Free day at the forecast peak. Tofuku-ji early, Rurikoin (reserve ahead), farewell dinner at <strong>Cenci</strong> (Italian 1★, easy GF, ≈ $350/couple).', ref: ['tofukuji', 'rurikoin', 'cenci-kyoto'] },
      { date: 'Sun 22', where: '✈', text: 'KIX→SFO Polaris, landing Sunday.', ref: [] },
    ],
    stays: ['aman-tokyo', 'gora-kadan', 'sowaka'],
    altStays: ['hotel-the-mitsui-kyoto', 'gora-byakudan'],
    dining: ['leffervescence', 'kikunoi-honten', 'kodaiji-jugyuan', 'cenci-kyoto', 'itoh-dining-nobu'],
    doing: ['hirata-sword', 'picchio-musasabi', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['eikando', 'tofukuji', 'kodaiji', 'philosophers-path', 'arashiyama', 'nara-deer', 'rurikoin', 'sanzen-in-ohara', 'byodo-in-uji', 'gion', 'lake-ashi', 'hakone-open-air-museum', 'meiji-jingu', 'omotesando-ginkgo', 'yanaka-tokyo'],
    costRows: [
      ['Flights (open-jaw business)', '$9,500'],
      ['Hotels — Aman 4n + Gora Kadan 2n (HB) + Sowaka 8n at pre-peak rates', '$17,000'],
      ['Dining (the two ryokan kaiseki nights are already included above)', '$4,200'],
      ['Experiences — sword $1,700, Heki kintsugi $600, kyudo $270, Karuizawa flying squirrels $170, owl café $60, monkey park $10', '$2,810'],
      ['Ground — Green Car, transfers, takkyubin', '$1,300'],
    ],
    costTotal: '≈ $34,800',
    levers: `<strong>The remaining budget levers:</strong> United or consolidator fares (−$2,000) and Gora Byakudan instead of Gora Kadan (−$1,300) would land it near $31,500. Aman Tokyo carries about $2,000 of the total across four nights; the Palace Hotel would give that back, though Kyoto is the bigger lever at eight nights. Sowaka is also cheaper on these dates than it was on peak ones, which is already priced in above. Going the other way, Kyoto at Hotel The Mitsui instead of Sowaka still adds $7,000–20,000.`,

    verdict: `<strong>The colour, honestly.</strong> Eight Kyoto nights across 14–21 November is the longest run of any option, and it straddles the turn: the northern districts — Takao, Kurama and Kibune, Ohara, Rurikoin — are at or near their best across the whole block, while Tofuku-ji, Eikandō and Kiyomizu come on toward the end of it without reaching full crest. 2026 is forecast late, and the crest lands while you are in Colorado.<br><br>What you get for staying put is depth rather than a peak: eight nights is enough to go back to somewhere twice, to lose a day to rain without it mattering, and to keep both Nara and Ohara. That is the argument for this over 1B and 1C, which trade Kyoto nights for a second destination.`,

    verdictTone: 'good',
  },

  // ═════════════════════════════════════════════════ 1C — variant of 1 ══
  {
    num: '1C',
    slug: 'momiji-then-the-coast',
    variantOf: 1,
    title: 'The Classic, then the Crab Coast',
    tagline: 'Four nights in Kyoto, then keep going west to the crab coast',

    dates: 'Sat Nov 7 → Sun Nov 22, 2026',
    length: '14 nights',
    route: ['Tokyo · 4n', 'Hakone · 2n', 'Kyoto · 4n', 'Kinosaki · 4n'],
    routeNote: 'Open-jaw, returning from KIX — home three days before Colorado',
    cost: '$34,600',
    costBand: '$33–35k',
    temp: '42–58°F — the coast is the cold end',
    tempStatus: 'ok',
    bestFor: 'Ending somewhere quiet, and eating crab',
    transport: {
      mode: 'Rail',
      text: `All rail. The new leg is the Limited Express Kinosaki, straight out of Kyoto and over the mountains to the coast in about 2h30. The one thing to plan properly is the last day: Kinosaki→Shin-Osaka on the Kounotori is 2h40, then the Haruka to KIX — <strong>about 4 hours door to gate</strong>. With a late-afternoon KIX departure you leave Kinosaki mid-morning, which is fine, but it is not a leg to improvise.`,
      ref: ['shinkansen-green-car', 'ana-the-room'],
    },
    hero: 'kinosaki',
    heroCard: ['nishimuraya-honkan', 'kinosaki', 'tofukuji'],
    pitch: `Kyoto cut to four nights, then straight past it to the Sea of Japan: <strong>Nishimuraya Honkan</strong>, a Relais &amp; Châteaux ryokan seven generations deep, in a canal town where you walk between the public bathhouses in a yukata. The trip ends in an onsen town instead of a city.<br><br>Re-dated to 7–22 November so it clears Thanksgiving. That puts Kyoto on <strong>14–17 November</strong> — the earliest Kyoto block of any option, which means the northern hills are your colour and the central temples are still coming on. It also puts Kinosaki on 18–21 November, and <strong>Matsuba crab season opens on the 6th</strong>, so you are comfortably inside it.`,

    days: [
      { date: 'Sat 7', where: '✈', text: 'SFO→HND, ANA The Room', ref: ['ana-the-room'] },
      { date: 'Sun 8', where: 'Tokyo', text: 'Land, private transfer, gentle evening. <strong>Aman Tokyo</strong>.', ref: ['aman-tokyo'] },
      { date: 'Mon 9', where: 'Tokyo', text: 'Meiji Jingu and the Jingu Gaien ginkgo. <em>They gold up around 20 Nov, so this early they are green-to-yellow rather than the corridor of gold.</em> Afternoon at <strong>Akiba Fukurou</strong>, the owl café. <em>No dinner booking: L\'Effervescence is closed Sundays and Mondays.</em>', ref: ['meiji-jingu', 'omotesando-ginkgo', 'akiba-fukurou'] },
      { date: 'Tue 10', where: 'Tokyo · Ome', text: '<strong>Hirata sword smithing</strong> out west — forge a small katana with the husband-and-wife smiths. Back in town for <strong>L\'Effervescence</strong>.', ref: ['hirata-sword', 'leffervescence'] },
      { date: 'Wed 11', where: 'Karuizawa', text: '<strong>Flying squirrels</strong> with Picchio, 16:00–17:30, back in Tokyo by about 19:15. <em>Note the margin: the season closes 30 November, so this is one of the last runs of the year. Book it first and build the week around it.</em>', ref: ['picchio-musasabi'] },
      { date: 'Thu 12', where: 'Hakone', text: 'Romancecar or private transfer. <strong>Gora Kadan</strong> — gluten-free kaiseki in the room, cypress onsen. <em>Hakone\'s own foliage peaks mid-November, so a week later you catch its tail rather than its crest.</em>', ref: ['gora-kadan'] },
      { date: 'Fri 13', where: 'Hakone', text: 'Open-Air Museum, Lake Ashi. Lunch at <strong>Itoh Dining by Nobu</strong>. Second kaiseki at the ryokan.', ref: ['hakone-open-air-museum', 'lake-ashi', 'itoh-dining-nobu'] },
      { date: 'Sat 14', where: 'Kyoto', text: 'Green Car Odawara→Kyoto. <strong>Sowaka</strong> in Gion, arriving at the front edge of peak colour. Evening Gion walk.', ref: ['sowaka', 'gion'] },
      { date: 'Sun 15', where: 'Kyoto', text: 'Early — 8am — Honen-in and the Philosopher\'s Path. <strong>Eikando</strong> illumination in the evening, at the densest forecast colour of the year. <strong>Kikunoi Honten</strong> dinner.', ref: ['philosophers-path', 'eikando', 'kikunoi-honten'] },
      { date: 'Mon 16', where: 'Kyoto', text: '<strong>Tofuku-ji</strong> at opening for the Tsutenkyo maples, <strong>Rurikoin</strong> if you reserved it. <strong>Heki kintsugi</strong> in the afternoon. <strong>Kodaiji Jugyuan</strong> dinner and the illumination next door.', ref: ['tofukuji', 'rurikoin', 'heki-kintsugi', 'kodaiji-jugyuan', 'kodaiji'] },
      { date: 'Tue 17', where: 'Kyoto · Arashiyama', text: '<strong>Iwatayama monkey park</strong> at opening, then the bamboo grove, Tenryu-ji and the Hozugawa. <strong>Kyudo</strong> late if you want it. Last Kyoto night.', ref: ['arashiyama-monkeys', 'arashiyama', 'kyudo'] },
      { date: 'Wed 18', where: '→ Kinosaki', text: 'Limited Express Kinosaki out of Kyoto, over the mountains to the coast, about 2h30. <strong>Nishimuraya Honkan</strong> — seven generations, a moss garden, bamboo-grove baths. First <strong>Matsuba crab</strong> kaiseki.', ref: ['nishimuraya-honkan', 'kinosaki'] },
      { date: 'Thu 19', where: 'Kinosaki', text: 'The point of the town: yukata, geta, and the <strong>public bathhouses</strong> along the willow canal — six of the seven are open, Sato-no-yu having been under renovation since 2024 — taken slowly across a day and an evening.', ref: ['kinosaki'] },
      { date: 'Fri 20', where: 'Toyooka', text: '<strong>Oriental white storks</strong> twenty minutes away — extinct in the wild here in 1971, bred back, and now nesting on towers over pesticide-free rice fields. <em>November is outside their breeding season: no chicks or nest activity, just birds working the flooded paddies plus the captive birds at the park. Closed Mondays.</em> Then the Genbudo basalt caves, or Izushi for its soba and castle town.', ref: ['toyooka-storks'] },
      { date: 'Sat 21', where: 'Kinosaki', text: 'Nothing scheduled. The Takeno coast if the weather is kind, the ropeway over the town if it is not, and the last crab dinner either way.', ref: ['nishimuraya-honkan'] },
      { date: 'Sun 22', where: '✈', text: 'Kounotori to Shin-Osaka, Haruka to KIX — leave mid-morning for a late-afternoon Polaris home.', ref: [] },
    ],
    stays: ['aman-tokyo', 'gora-kadan', 'sowaka', 'nishimuraya-honkan'],
    altStays: [],
    dining: ['leffervescence', 'kikunoi-honten', 'kodaiji-jugyuan', 'itoh-dining-nobu'],
    doing: ['hirata-sword', 'picchio-musasabi', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['kinosaki', 'toyooka-storks', 'tofukuji', 'eikando', 'kodaiji', 'philosophers-path', 'arashiyama', 'rurikoin', 'gion', 'lake-ashi', 'hakone-open-air-museum', 'meiji-jingu', 'omotesando-ginkgo'],
    costRows: [
      ['Flights (open-jaw business)', '$9,500'],
      ['Hotels — Aman 4n + Gora Kadan 2n (HB) + Sowaka 4n + Nishimuraya 4n (HB)', '$17,500'],
      ['Dining — only four Kyoto dinners; six of the fourteen nights are half board', '$3,400'],
      ['Experiences — sword $1,700, Heki kintsugi $600, kyudo $270, flying squirrels $170, owl café $60, monkey park $10', '$2,810'],
      ['Ground — Green Car, the Kinosaki legs, transfers, takkyubin', '$1,400'],
    ],
    costTotal: '≈ $34,600',
    levers: `<strong>If you want more Kyoto than this.</strong> Four nights is the shortest Kyoto block in the set, and on 14–17 November it is also the earliest — you would be relying almost entirely on Takao, Kurama and Ohara for colour. Itinerary 1B keeps a second destination but gives Kyoto five nights three days later, which is a meaningfully better window. This one is for you if the <em>ending</em> matters more than the Kyoto count.`,

    verdict: `<strong>What this buys.</strong> A genuinely different ending — a thirteen-century-old bathhouse town on the Sea of Japan, in crab season, at a family ryokan seven generations deep — plus the Toyooka storks, and the cheapest total of the three Classic forks at about $34,600.<br><br><strong>What it costs.</strong> The earliest and shortest Kyoto of any option: four nights on 14–17 November, leaning on the northern hills for colour. Kikunoi, Jugyuan, the kintsugi, Arashiyama and Tofuku-ji in three and a half days, with no slack for weather. And the last day is about four hours of trains from Kinosaki to KIX, which needs booking rather than improvising.`,

    verdictTone: 'note',
  },

  // ══════════════════════════════════════════════════════════════ 2 ══
  {
    num: 2,
    slug: 'crafts-crab-snow-monkeys',
    title: 'Crafts, Crab & Snow Monkeys',
    tagline: 'Two wildlife days on one rail line, crab week, and Kenrokuen at peak',
    dates: 'Sat Nov 7 → Sun Nov 22, 2026',
    length: '14 nights',
    route: ['Tokyo · 3n', 'Shibu Onsen · 2n', 'Kanazawa · 2n', 'Kaga · 2n', 'Kyoto · 5n'],
    routeNote: 'Out of KIX',
    cost: '$31,200',
    costBand: '$30–32k',
    temp: 'Mostly good; Nagano in the 40s',
    tempStatus: 'ok',
    bestFor: 'Wildlife, crab season, Kenrokuen at peak',
    transport: {
      mode: 'Rail + one car day',
      text: `The Hokuriku shinkansen's <strong>Gran Class</strong> — attendant service, about $190 for the Tokyo→Kanazawa leg — is the best train seat in the country and exists only on this line. The route is partly built around it. The local Nagaden line plus a taxi covers the monkey park; no rental needed.`,
      ref: ['gran-class', 'shinkansen-green-car'],
    },
    hero: 'kenrokuen',
    heroCard: ['snow-monkeys', 'zeniya-kanazawa', 'beniya-mukayu'],
    pitch: `Four regions, the best train seat in Japan, and a set of alignments that only work in this exact fortnight: Kenrokuen at its mid-November peak and snow crab season opening the week before you arrive. Trimming the craft workshops changed what this trip is about — it used to be the densest craft run of the set, and now its real distinction is wildlife. The Hokuriku line happens to thread both Karuizawa and Nagano, so the flying squirrels and the snow monkeys sit two days apart on the same rails. The trade is Kyoto — you arrive Nov 17–22, colour building but likely just before the forecast peak, in exchange for rooms about $300/night cheaper.`,
    days: [
      { date: 'Sat 7', where: '✈', text: 'SFO→HND', ref: ['ana-the-room'] },
      { date: 'Sun 8', where: 'Tokyo', text: 'Land. <strong>Aman Tokyo</strong>.', ref: ['aman-tokyo'] },
      { date: 'Mon 9', where: 'Karuizawa', text: '<strong>Akiba Fukurou</strong>, the owl café, in the morning — then the shinkansen to Karuizawa for Picchio\'s <strong>musasabi watching tour</strong>: a camera inside the nest, then the animal leaving at dusk to glide. 16:00–17:30, back in Tokyo by about 19:15. <em>Monday takes this day because the 19:15 return rules out a booked dinner — and because L\'Effervescence is closed Sundays and Mondays. Season closes 30 November.</em>', ref: ['akiba-fukurou', 'picchio-musasabi'] },
      { date: 'Tue 10', where: 'Tokyo · Ome', text: '<strong>Hirata sword smithing</strong> in the morning out west. <strong>L\'Effervescence</strong> dinner with its printed GF menu — the only night in this Tokyo block it is open.', ref: ['hirata-sword', 'leffervescence'] },
      { date: 'Wed 11', where: 'Nagano', text: 'Gran Class Tokyo→Nagano (1h20) — back out along the same line, through Karuizawa. Zenko-ji. On to <strong>Kokuya</strong> in Shibu Onsen, a 400-year-old ryokan with the master key to the town\'s nine bathhouses.', ref: ['gran-class', 'zenkoji', 'kokuya'] },
      { date: 'Thu 12', where: 'Jigokudani', text: '<strong>Snow monkey day.</strong> <em>Expectation set: the park is open and the monkeys are present and active, but they rarely soak before real cold — you may get a dusting of snow, not the steaming-bath postcard. That is December to February.</em>', ref: ['snow-monkeys'] },
      { date: 'Fri 13', where: 'Kanazawa', text: 'Gran Class Nagano→Kanazawa (1h10). Higashi Chaya and the gold-leaf district. Hyatt Centric or similar.', ref: ['higashi-chaya', 'hyatt-centric-kanazawa'] },
      { date: 'Sat 14', where: 'Kanazawa', text: 'Kenrokuen at its <strong>mid-November peak</strong>, plus the evening illumination. <strong>Zeniya</strong> dinner — 2★ Relais & Châteaux kaiseki with no fixed menu, so the chef tailors per guest, which is the best GF signal in the city. <strong>Crab season opened Nov 6</strong>, and kano-gani is naturally gluten-free.', ref: ['kenrokuen', 'zeniya-kanazawa'] },
      { date: 'Sun 15', where: 'Kaga', text: 'Local train to Yamashiro Onsen. <strong>Beniya Mukayu</strong> — Relais & Châteaux, gluten-free kaiseki with notice, private onsen.', ref: ['beniya-mukayu'] },
      { date: 'Mon 16', where: 'Kaga', text: 'Second Mukayu night, deliberately empty: morning yoga, the library, the private rotenburo. The Kutani ware and Kaga yuzen workshops nearby are dropped along with the other craft modules — this is the day the trip stops moving.', ref: ['beniya-mukayu'] },
      { date: 'Tue 17', where: 'Kyoto', text: 'Thunderbird express, about 2 hours. <strong>Sowaka</strong>, at pre-peak rates.', ref: ['sowaka'] },
      { date: 'Wed 18', where: 'Kyoto', text: '<strong>Kikunoi Honten</strong> dinner. Early morning on the Philosopher\'s Path.', ref: ['kikunoi-honten', 'philosophers-path'] },
      { date: 'Thu 19', where: 'Kyoto · Arashiyama', text: '<strong>Iwatayama monkey park</strong> at opening — wild macaques on the hilltop with the city behind them — then the bamboo grove and Tenryu-ji, with Arashiyama\'s colour building.', ref: ['arashiyama-monkeys', 'arashiyama'] },
      { date: 'Fri 20', where: 'Kyoto · Ohara', text: 'Ohara: <strong>Sanzen-in</strong>, the moss garden and the jizo figures, forty minutes north of the city and far quieter than it.', ref: ['sanzen-in-ohara'] },
      { date: 'Sat 21', where: 'Kyoto', text: '<strong>Heki kintsugi</strong> — the one craft workshop kept — and <strong>kyudo</strong> if you want the morning filled. <strong>Kodaiji Jugyuan</strong> farewell dinner plus the illumination next door.', ref: ['heki-kintsugi', 'kyudo', 'kodaiji-jugyuan', 'kodaiji'] },
      { date: 'Sun 22', where: '✈', text: 'KIX→SFO', ref: [] },
    ],
    stays: ['aman-tokyo', 'kokuya', 'hyatt-centric-kanazawa', 'beniya-mukayu', 'sowaka'],
    altStays: [],
    dining: ['leffervescence', 'zeniya-kanazawa', 'kikunoi-honten', 'kodaiji-jugyuan'],
    doing: ['snow-monkeys', 'picchio-musasabi', 'hirata-sword', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['kenrokuen', 'higashi-chaya', 'zenkoji', 'arashiyama', 'sanzen-in-ohara', 'philosophers-path', 'kodaiji', 'gion'],
    costRows: [
      ['Flights', '$9,500'],
      ['Hotels — Aman 3n + Kokuya 2n (HB) + Kanazawa 1n + Mukayu 2n (HB) + Sowaka 5n', '$13,900'],
      ['Dining', '$3,800'],
      ['Experiences — sword $1,700, Heki kintsugi $600, kyudo $270, flying squirrels $170, owl café $60, both monkey parks $30', '$2,830'],
      ['Ground — Gran Class, expresses, transfers', '$1,200'],
    ],
    costTotal: '≈ $31,200',
    levers: `Kyoto days land Nov 17–22 — colour building but likely just before the forecast peak, in exchange for roughly $300/night cheaper rooms and the full Kanazawa crab-and-Kenrokuen alignment.`,
    verdict: `<strong>This one changed the most.</strong> Its old selling point was being the densest craft itinerary, and that is gone — Mutoh kintsugi, the Raku kiln, the indigo and the Kutani/yuzen day all came out. What is left is arguably a better trip: three wildlife encounters (Karuizawa flying squirrels, Jigokudani macaques, Iwatayama macaques), crab season, Kenrokuen at peak, and the country's best train seat. The craft cuts took $1,100 off, though moving Tokyo to Aman has since put $1,500 back on. Watch the Nov 21–23 holiday weekend crowds at the tail end.`,
    verdictTone: 'good',
  },

  // ══════════════════════════════════════════════════════════════ 3 ══
  {
    num: 3,
    slug: 'wildlife-north',
    title: 'Wildlife North',
    tagline: 'Built around the one experience that got five thumbs up',
    dates: 'Sat Nov 7 → Sun Nov 22, 2026',
    length: '14 nights',
    route: ['Tokyo · 1n', 'E. Hokkaido · 4n', 'Kyoto · 9n'],
    routeNote: 'Open-jaw, returning from KIX — home three days before Colorado',
    cost: '$30,200',
    costBand: '$29–31k',
    temp: 'Hokkaido 20–40°F',
    tempStatus: 'warn',
    bestFor: 'The Ezo momonga — the only route that shows you that species',
    transport: {
      mode: 'Fly + self-drive + rail',
      text: `Eastern Hokkaido is effectively car-only, and it is where your road-trip instincts pay off: empty, beautiful roads. Rentals come with studless tyres fitted free. Drive in daylight only — sunset is about 4pm — and watch for dawn black ice. HND→Kushiro is 1h40 at $100–125 per person; returning is Kushiro→HND→ITM to reach Kyoto.`,
      ref: ['lexus-nx-japan', 'ana-the-room'],
    },
    hero: 'ezo-momonga',
    heroCard: ['tsurui-cranes', 'hinanoza', 'tofukuji'],
    pitch: `Ashly's most-wanted item on the entire wish list is the Ezo flying squirrel, marked with five thumbs up. This itinerary is the answer to that: four days in eastern Hokkaido with a guide, then nine nights in Kyoto. It is the cheapest route that delivers the momonga specifically — but the Thanksgiving re-date costs it more than it costs the others, and the honesty box below explains why.`,

    days: [
      { date: 'Sat 7', where: '✈', text: 'SFO→HND', ref: ['ana-the-room'] },
      { date: 'Sun 8', where: 'Tokyo', text: 'Land. <strong>Aman Tokyo</strong>, one night. Recovery evening.', ref: ['aman-tokyo'] },
      { date: 'Mon 9', where: '→ Hokkaido', text: '<strong>Akiba Fukurou</strong>, the owl café, in the morning — Akihabara is on the way to Haneda — then HND→Kushiro in the afternoon. Pick up the 4WD. <strong>Akan Tsuruga Bessou Hinanoza</strong> on Lake Akan, 25 suites, every one with a private onsen.', ref: ['akiba-fukurou', 'hinanoza', 'lake-akan'] },
      { date: 'Tue 10', where: 'Akan / Tsurui', text: '<strong>Red-crowned cranes at the Tsurui-Ito sanctuary</strong> — feeding season starts mid-to-late November, so numbers are building, not yet the January–February 300-bird spectacle. Ural owl roost plus Ezo deer and fox with a local guide.', ref: ['tsurui-cranes'] },
      { date: 'Wed 11', where: 'Kussharo', text: '<strong>Whooper swans arriving at Lake Kussharo</strong> — the Kotan and Sunayu lakeside hot springs. Mt Io. Second night at Hinanoza.', ref: ['lake-kussharo', 'hinanoza'] },
      { date: 'Thu 12', where: 'Kushiro', text: 'Kushiro-Shitsugen wetland boardwalks. At dusk: <strong>the Ezo flying squirrel session</strong> — momonga emerge about 10 minutes after sunset at monitored burrows, and guides run these year-round with high success at known dens (≈ $200–300/couple). Overnight in Kushiro, or a third night at Hinanoza.', ref: ['kushiro-shitsugen', 'ezo-momonga', 'kushiro-stay'] },
      { date: 'Fri 13', where: '→ Kyoto', text: 'Morning momonga backup slot — weather insurance, since windy or rainy nights get cancelled. Fly Kushiro→HND→ITM. <strong>Sowaka</strong> in Kyoto.', ref: ['ezo-momonga', 'sowaka'] },
      { date: 'Sat 14 – Fri 20', where: 'Kyoto', text: 'The Itinerary 1 Kyoto week, compressed and now with room to breathe: <strong>Kikunoi</strong>, <strong>Jugyuan</strong>, <strong>Heki kintsugi</strong>, <strong>kyudo</strong>, the <strong>Iwatayama monkey park</strong> above Arashiyama, a day in <strong>Nara</strong> among the deer, and Eikando and Rurikoin — with the final days riding into forecast peak colour.', ref: ['kikunoi-honten', 'kodaiji-jugyuan', 'heki-kintsugi', 'kyudo', 'arashiyama-monkeys', 'nara-deer', 'eikando', 'rurikoin'], span: true },
      { date: 'Sat 21', where: 'Kyoto', text: 'Peak-colour free day. <strong>Cenci</strong> farewell.', ref: ['tofukuji', 'cenci-kyoto'] },
      { date: 'Sun 22', where: '✈', text: 'KIX→SFO', ref: [] },
    ],
    stays: ['aman-tokyo', 'hinanoza', 'kushiro-stay', 'sowaka'],
    altStays: [],
    dining: ['kikunoi-honten', 'kodaiji-jugyuan', 'cenci-kyoto'],
    doing: ['ezo-momonga', 'tsurui-cranes', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['lake-akan', 'lake-kussharo', 'kushiro-shitsugen', 'nara-deer', 'eikando', 'tofukuji', 'rurikoin', 'arashiyama', 'gion', 'kodaiji'],
    costRows: [
      ['Flights, international', '$9,500'],
      ['Domestic flights — HND–Kushiro, Kushiro–ITM via HND', '$900'],
      ['Hotels — Aman 1n + Hinanoza 3n (HB) + Kushiro 1n + Sowaka 9n', '$12,900'],
      ['Car — 4WD 4 days plus fuel and tolls', '$700'],
      ['Dining', '$3,600'],
      ['Experiences and guides — Hokkaido wildlife guiding $750, Heki kintsugi $600, kyudo $270, owl café $60, monkey park $10', '$1,690'],
      ['Ground', '$900'],
    ],
    costTotal: '≈ $30,200',
    levers: `Shiretoko is deliberately absent — the pass closes in early November, the Five Lakes trails close in late November, bear cruises are done, and the drift-ice eagles are a February show.`,
    verdict: `<strong>The re-date hurts this one most, and you should know that before choosing it.</strong> Moving to 7–22 November puts eastern Hokkaido on 8–12 November, and <strong>crane feeding at Tsurui does not really begin until mid-to-late November</strong>. On these dates you would be there before the birds gather — a handful rather than a congregation. The whooper swans at Kussharo are early too.<br><br>What survives intact is the <strong>Ezo momonga</strong>, which guides run year-round at monitored dens with a high success rate, and that was always the point of this itinerary. The foxes, deer and owls are unaffected.<br><br>So the choice sharpens: if the flying squirrel alone justifies Hokkaido, this still works and it is the only route that shows you <em>that</em> species. If you wanted the cranes as well, they need a January or February trip — and Karuizawa now puts a different flying squirrel on itineraries 1, 1B, 1C and 5 for about $170.`,

    verdictTone: 'warn',
  },

  // ══════════════════════════════════════════════════════════════ 4 ══
  {
    num: 4,
    slug: 'southern-warmth',
    title: 'Southern Warmth',
    tagline: 'The only one entirely inside your temperature band — and the best drive',
    dates: 'Sat Oct 31 → Sun Nov 15, 2026',
    length: '14 nights',
    route: ['Fukuoka · 2n', 'Kurokawa · 2n', 'Kagoshima · 1n', 'Yakushima · 3n', 'Kyoto · 6n'],
    routeNote: 'Open-jaw, returning from KIX',
    cost: '$28,200',
    costBand: '$27–29k',
    temp: '55–70°F throughout',
    tempStatus: 'best',
    bestFor: 'Warmth, road trip, most headroom in budget',
    transport: {
      mode: 'Fly + self-drive Kyushu',
      text: `The truest successor to your France, UK and Germany format: a Lexus through Aso caldera country is one of Japan's great drives, and rural onsen are awkward without a car. This is also the warmest itinerary — 55–70°F nearly throughout, and the only one fully inside the seeds temperature band.`,
      ref: ['lexus-nx-japan', 'ana-the-room'],
    },
    hero: 'aso-caldera',
    heroCard: ['gekkoju', 'shiratani-unsuikyo', 'sankara-yakushima'],
    pitch: `Start in Kyushu at 65°F, drive a Lexus across one of the largest volcanic calderas on earth, sleep in a villa with a private hot spring in the woods at Kurokawa, fly to a subtropical island of thousand-year-old cedars, and finish with six nights in Kyoto at pre-peak prices. It is the cheapest of them all, the warmest by a distance, and the closest in shape to the trips you have actually enjoyed before. The cost is that it skips Tokyo entirely — which means no sword smithing.`,
    days: [
      { date: 'Sat 31', where: '✈', text: 'SFO→HND, connecting HND→Fukuoka (or a through-ticket)', ref: ['ana-the-room'] },
      { date: 'Sun 1', where: 'Fukuoka', text: '<strong>The Ritz-Carlton Fukuoka</strong>. Yatai-district evening walk — for GF, stick to the counters rather than the stalls.', ref: ['ritz-carlton-fukuoka', 'fukuoka-yatai'] },
      { date: 'Mon 2', where: 'Fukuoka', text: '<strong>Goh</strong> dinner — Asia\'s 50 Best, 14 seats, single seating; French-Japanese means an easy gluten-free dialogue. <strong>The email window opens 60 days out — set a calendar alarm for 2 September</strong>, and target a Tuesday or Wednesday.', ref: ['goh-fukuoka'] },
      { date: 'Tue 3', where: '→ Kurokawa', text: 'Pick up the <strong>Lexus NX</strong> (Toyota Rent a Car premium, ≈ $250/day). Drive via Yufuin, 2.5 scenic hours. <strong>Gekkoju</strong> — 8 private villas, each with its own open-air onsen. Foliage here runs late Oct to mid Nov, so this is on time.', ref: ['lexus-nx-japan', 'yufuin', 'gekkoju'] },
      { date: 'Wed 4', where: 'Aso', text: 'The Aso caldera and the Kusasenri grasslands — the road-trip day. Kurokawa town stroll in yukata, with the rotenburo-hopping pass.', ref: ['aso-caldera', 'kurokawa-onsen-town'] },
      { date: 'Thu 5', where: '→ Kagoshima', text: 'Drive south, about 3 hours, via Kirishima shrine country. Drop the car. Shiroyama Hotel, or a night by the airport. Sakurajima views.', ref: ['kirishima', 'shiroyama-kagoshima', 'sakurajima'] },
      { date: 'Fri 6', where: 'Yakushima', text: '40-minute JAC turboprop. <strong>Sankara Hotel & Spa</strong> — Small Luxury Hotels, from the seeds list; suites include dinner at okas. It publishes its gluten-free accommodation outright.', ref: ['sankara-yakushima', 'okas-sankara'] },
      { date: 'Sat 7', where: 'Yakushima', text: '<strong>Shiratani Unsuikyo</strong> guided hike — the mossy "Princess Mononoke" forest. November is Yakushima\'s driest, clearest season.', ref: ['shiratani-unsuikyo'] },
      { date: 'Sun 8', where: 'Yakushima', text: 'Coastal loop drive: Oko Falls, Nagata beach, an onsen. okas French-Yakushima dinner.', ref: ['yakushima-coast', 'okas-sankara'] },
      { date: 'Mon 9', where: '→ Kyoto', text: 'Fly Yakushima→Kagoshima→ITM. <strong>Sowaka</strong> — early-to-mid November is <em>pre-peak pricing</em>, the quiet luxury window.', ref: ['sowaka'] },
      { date: 'Tue 10', where: 'Kyoto · Arashiyama', text: '<strong>Iwatayama monkey park</strong> at opening, then early Arashiyama — first colour around Nov 10–15 at the altitude edges. <strong>Kikunoi Honten</strong> in the evening.', ref: ['arashiyama-monkeys', 'arashiyama', 'kikunoi-honten'] },
      { date: 'Wed 11', where: 'Nara', text: '<strong>Nara</strong>: sika deer loose among the temples, Todai-ji\'s Great Buddha hall and the lantern avenue at Kasuga Taisha, 45 minutes each way. Gion in the evening.', ref: ['nara-deer', 'gion'] },
      { date: 'Thu 12', where: 'Kyoto', text: '<strong>Heki kintsugi</strong> in the morning — the one craft workshop kept. Eikando illumination opening nights.', ref: ['heki-kintsugi', 'eikando'] },
      { date: 'Fri 13', where: 'Kyoto · Ohara', text: 'Ohara and <strong>Sanzen-in</strong> — the moss garden and its jizo figures, well north of the city and quiet.', ref: ['sanzen-in-ohara'] },
      { date: 'Sat 14', where: 'Kyoto', text: '<strong>Kyudo</strong> session. <strong>Kodaiji Jugyuan</strong> farewell dinner plus the Kodai-ji illumination.', ref: ['kyudo', 'kodaiji-jugyuan', 'kodaiji'] },
      { date: 'Sun 15', where: '✈', text: 'KIX→SFO Polaris', ref: [] },
    ],
    stays: ['ritz-carlton-fukuoka', 'gekkoju', 'shiroyama-kagoshima', 'sankara-yakushima', 'sowaka'],
    altStays: [],
    dining: ['goh-fukuoka', 'okas-sankara', 'kikunoi-honten', 'kodaiji-jugyuan'],
    doing: ['shiratani-unsuikyo', 'arashiyama-monkeys', 'heki-kintsugi', 'kyudo'],
    places: ['aso-caldera', 'kurokawa-onsen-town', 'yufuin', 'sakurajima', 'kirishima', 'fukuoka-yatai', 'yakushima-coast', 'nara-deer', 'arashiyama', 'eikando', 'sanzen-in-ohara', 'gion', 'kodaiji'],
    costRows: [
      ['Flights, international (open-jaw HND in / KIX out)', '$9,500'],
      ['Domestic — HND–FUK, KOJ–Yakushima, Yakushima–KOJ–ITM', '$1,300'],
      ['Hotels — Ritz 2n + Gekkoju 2n (HB) + Kagoshima 1n + Sankara 3n + Sowaka 6n', '$10,600'],
      ['Car — Lexus 3 days, tolls and fuel, plus the Yakushima rental', '$1,100'],
      ['Dining', '$3,600'],
      ['Experiences — Heki kintsugi $600, Yakushima guide $300, kyudo $270, monkey park $10', '$1,180'],
      ['Ground', '$900'],
    ],
    costTotal: '≈ $28,200',
    levers: `In budget with headroom to about $27.5k via United or consolidator fares. Warmest, best road-trip content, and Sankara, Goh and Gekkoju are all seed-adjacent wins.`,
    verdict: `<strong>Still the cheapest and warmest — but the cuts helped it least, and the additions skip it entirely.</strong> It only loses $1,300 of activity spend because it never had the matcha or the Tokyo kintsugi, and because <strong>it skips Tokyo it is now the only route with no flying squirrel and no owl café</strong>. Its wildlife is the Iwatayama macaques, the Nara deer and whatever the Yakushima forest offers. Adding a 2-night Tokyo block (about $4,000) would buy back the sword smithing, the owl café and the Karuizawa flying squirrels in one move — that lever is worth more now than it was. The other trades are unchanged: Kyoto at building colour rather than peak, compensated by lower rates and thinner crowds. Seven Stars, also from the seeds, lives in Kyushu, but its waitlist runs about two years and October 2026 cabins are effectively gone.`,
    verdictTone: 'good',
  },

  // ══════════════════════════════════════════════════════════════ 5 ══
  {
    num: 5,
    slug: 'grand-tour',
    title: 'The Grand Tour',
    tagline: 'The stretch. Everything, at the cost of both budget rules',
    dates: 'Sat Oct 31 → Thu Nov 19, 2026',
    length: '20 days / 18 nights',
    route: ['Tokyo · 3n', 'E. Hokkaido · 4n', 'Kyoto · 7n', 'Hakone · 2n', 'Tokyo · 2n'],
    routeNote: 'Out of HND, landing Thursday — home six days before Colorado',
    cost: '$37,000',
    costBand: '$36–39k',
    temp: 'Mixed',
    tempStatus: 'warn',
    bestFor: 'Everything — breaks budget and the Sat/Sun return',
    transport: {
      mode: 'Fly + Hokkaido self-drive + rail',
      text: `The everything trip: momonga and cranes <em>and</em> the densest peak-Kyoto colour (Nov 29 – Dec 3 forecast maximum) <em>and</em> Gora Kadan. It exists to show what the window physically allows.`,
      ref: ['ana-the-room', 'lexus-nx-japan', 'shinkansen-green-car'],
    },
    hero: 'rurikoin',
    heroCard: ['ezo-momonga', 'gora-kadan', 'eikando'],
    pitch: `It is still the only single-trip answer to "Hokkaido plus Kyoto plus Gora Kadan." Twenty days: the Tokyo crafts block, the Hokkaido wildlife loop, seven Kyoto nights, and two closing kaiseki nights at Gora Kadan. Re-dated to 31 October – 19 November so it clears Thanksgiving with six days to spare.<br><br>The cost of that shift is real and falls on both ends: eastern Hokkaido on 4–7 November is <strong>well before the cranes gather</strong>, and Kyoto on 8–14 November catches the northern hills turning but leaves the city temples early. This is now the trip that sees the most places, not the trip that sees them at their best.`,

    flow: `Tokyo — Hirata sword, the owl café, a Karuizawa day for the musasabi, L'Effervescence → fly to Kushiro for Hinanoza, the Tsurui cranes and the momonga session, exactly as in Itinerary 3 → fly to Kyoto for seven nights riding into the forecast crest, with Kikunoi, Jugyuan, the Heki kintsugi, kyudo, the Iwatayama macaques, Nara and the illuminations → Gora Kadan for two kaiseki nights → HND→SFO on Thursday 3 December. Both flying squirrel species, in one trip.`,
    days: [
      { date: 'Sat 31 Oct – Tue 3 Nov', where: 'Tokyo · Karuizawa', text: 'Land and settle at the <strong>Aman Tokyo</strong>. <strong>Hirata sword smithing</strong> in Ome, <strong>Akiba Fukurou</strong> the owl café, a day out to Karuizawa for the <strong>flying squirrels</strong>, and <strong>L\'Effervescence</strong>. This is the only route with enough Tokyo time left over for teamLab or a Yanaka afternoon.', ref: ['aman-tokyo', 'hirata-sword', 'akiba-fukurou', 'picchio-musasabi', 'leffervescence', 'teamlab'], span: true },
      { date: 'Wed 4 – Sat 7', where: 'E. Hokkaido', text: 'Fly to Kushiro, pick up the 4WD. <strong>Hinanoza</strong> on Lake Akan, the <strong>Tsurui cranes</strong>, the swans at Kussharo, and the <strong>Ezo flying squirrel</strong> session at dusk — as in Itinerary 3, with a backup night for weather.', ref: ['hinanoza', 'tsurui-cranes', 'lake-kussharo', 'ezo-momonga'], span: true },
      { date: 'Sun 8 – Fri 13', where: 'Kyoto', text: 'Six nights at <strong>Sowaka</strong> riding into the forecast crest: <strong>Kikunoi</strong>, <strong>Jugyuan</strong>, <strong>Heki kintsugi</strong>, <strong>kyudo</strong>, the <strong>Iwatayama monkey park</strong>, a day in <strong>Nara</strong>, Ohara, and the Eikando and Kodai-ji illuminations at their peak.', ref: ['sowaka', 'kikunoi-honten', 'kodaiji-jugyuan', 'heki-kintsugi', 'kyudo', 'arashiyama-monkeys', 'nara-deer', 'eikando', 'rurikoin', 'tofukuji'], span: true },
      { date: 'Sat 14 – Mon 16', where: 'Kyoto → Hakone', text: 'The last Kyoto days at the densest forecast colour, then the shinkansen to <strong>Gora Kadan</strong> for two kaiseki nights and the cypress onsen.', ref: ['gora-kadan', 'lake-ashi'], span: true },
      { date: 'Tue 17 – Thu 19', where: 'Hakone → Tokyo → ✈', text: 'Back to Tokyo for a final night, then HND→SFO, landing Thursday 19 November.', ref: ['aman-tokyo'], span: true },
    ],
    stays: ['aman-tokyo', 'hinanoza', 'sowaka', 'gora-kadan'],
    altStays: [],
    dining: ['leffervescence', 'kikunoi-honten', 'kodaiji-jugyuan'],
    doing: ['ezo-momonga', 'tsurui-cranes', 'picchio-musasabi', 'hirata-sword', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['rurikoin', 'eikando', 'tofukuji', 'kodaiji', 'nara-deer', 'lake-akan', 'lake-kussharo', 'lake-ashi', 'gion', 'arashiyama'],
    costRows: [
      ['Flights, international plus domestic', '$10,800'],
      ['Hotels — 17 nights: Aman 3 + Hinanoza 3 + Sowaka 6 + Gora Kadan 2 + Tokyo 1', '$21,000'],
      ['Dining, experiences, car and ground', '$5,200'],
    ],
    costTotal: '≈ $37,000',
    levers: `The cuts took $4,000 off, and the Aman swap put $1,500 back on. Cutting Hakone as well (−$3,500) lands it near $33,500 — but Gora Kadan is half the reason this itinerary exists.`,
    verdict: `<strong>Still breaks the budget and still lands on a Thursday</strong> — both of which it always did. What has changed is the seasonal case for it. It was built to be the one trip that caught peak Kyoto <em>and</em> the Hokkaido wildlife; with peak Kyoto unavailable this year and Hokkaido now visited before the cranes arrive, its argument is mostly about breadth and the two Gora Kadan nights at the end. If breadth is what you want, it delivers. If you want any single part of it at its best, one of the shorter routes does that better and for less.`,

    verdictTone: 'warn',
  },
];

// Every wish from seeds.md, checked against each itinerary.
// `has` is an entity slug looked up in the itinerary's own lists; `manual` overrides per itinerary number.
export const wishlist = [
  { label: 'Kikunoi Honten', note: 'named in seeds', has: 'kikunoi-honten' },
  { label: 'Kodaiji Jugyuan', note: 'named in seeds', has: 'kodaiji-jugyuan' },
  { label: 'Gora Kadan', note: 'named in seeds', has: 'gora-kadan' },
  { label: 'A Relais & Châteaux stay', note: 'seeds: “anything in R&C Japan”', manual: { 1: 'yes', '1B': 'yes', '1C': 'yes', 2: 'yes', 3: 'no', 4: 'no', 5: 'yes' }, why: { '1B': 'two of them — Gora Kadan and Myojinkan', '1C': 'two — Gora Kadan and Nishimuraya', 3: 'Hinanoza is the ceiling out east', 4: 'Sankara is SLH, not R&C' } },
  { label: 'A Michelin 3-Key hotel', note: 'seeds: favourite is Auberge du Soleil', manual: { 1: 'yes', '1B': 'yes', '1C': 'yes', 2: 'yes', 3: 'yes', 4: 'no', 5: 'yes' }, why: { 4: 'skips Tokyo; Sankara holds 1 Key' } },
  { label: 'Hirata sword smithing', note: 'Ashly 👍', has: 'hirata-sword' },
  { label: 'Kintsugi', note: 'Ashly 👍👍 — the deep Kyoto one only', has: 'heki-kintsugi' },
  { label: 'Kyudo', note: 'named in seeds 👍', has: 'kyudo' },
  { label: 'An owl café', note: 'Ashly asked for this', has: 'akiba-fukurou' },
  { label: 'A flying squirrel', note: 'Ashly 👍×5 — the top wish', has: ['ezo-momonga', 'picchio-musasabi'], why: { 1: 'musasabi, Karuizawa', '1B': 'musasabi, Karuizawa', '1C': 'musasabi — but 5 days before the season shuts', 2: 'musasabi, Karuizawa', 3: 'the Ezo momonga itself', 4: 'no Tokyo, so no Karuizawa', 5: 'both species' } },
  { label: 'Wildlife photography', note: 'a stated interest', manual: { 1: 'yes', '1B': 'yes', '1C': 'part', 2: 'yes', 3: 'yes', 4: 'part', 5: 'yes' }, why: { 1: 'squirrels, Nara deer, macaques', '1B': 'squirrels and macaques; no Nara', '1C': 'squirrels, macaques, Toyooka storks', 2: 'squirrels + two macaque troops', 3: 'momonga, cranes, swans', 4: 'macaques and Nara deer only', 5: 'everything' } },
  { label: 'Snow monkeys', note: 'Ashly 👍', has: 'snow-monkeys' },
  { label: 'Crane photography', note: 'named in seeds', has: 'tsurui-cranes' },
  { label: 'Sankara Yakushima', note: 'named in seeds', has: 'sankara-yakushima' },
  { label: 'Raku pottery, Shoraku kiln', note: 'in seeds — you cut it', manual: { 1: 'no', '1B': 'no', '1C': 'no', 2: 'no', 3: 'no', 4: 'no', 5: 'no' }, why: { 1: 'cut: three ceramics workshops was too many' } },
  { label: 'Indigo dyeing', note: 'in seeds — you cut it', manual: { 1: 'no', '1B': 'no', '1C': 'no', 2: 'no', 3: 'no', 4: 'no', 5: 'no' }, why: { 1: 'cut, though Ohara stays' } },
  { label: 'Uji matcha experience', note: 'in seeds — you cut it', manual: { 1: 'no', '1B': 'no', '1C': 'no', 2: 'no', 3: 'no', 4: 'no', 5: 'no' }, why: { 1: 'cut: not worth $2,600' } },
  { label: '55–75°F throughout', note: 'a stated requirement', manual: { 1: 'part', '1B': 'no', '1C': 'part', 2: 'part', 3: 'no', 4: 'yes', 5: 'no' }, why: { 1: '45–65°F — a little under', '1B': 'the Alps stop is near freezing at night', '1C': 'the Sea of Japan coast in late November', 2: 'Nagano in the 40s', 3: 'Hokkaido 20–40°F', 5: 'mixed — Hokkaido in early November' } },
  // These are each itinerary's own costTotal. They drifted badly once — 1B alone appeared as three
  // different numbers across the site — so if a cost table changes, change this row in the same commit.
  { label: 'Inside the $30k budget', note: 'stated $15–30k', manual: { 1: 'no', '1B': 'no', '1C': 'no', 2: 'no', 3: 'part', 4: 'yes', 5: 'no' }, why: { 1: '$34.8k', '1B': '$36.2k', '1C': '$34.6k', 2: '$31.2k', 3: '$30.2k — $200 over', 4: '$28.2k', 5: '$37.0k' } },
  { label: 'Leave and return Sat/Sun', note: 'stated preference', manual: { 1: 'yes', '1B': 'yes', '1C': 'yes', 2: 'yes', 3: 'yes', 4: 'yes', 5: 'no' }, why: { 5: 'lands Thursday 3 December' } },
  { label: 'Autumn colour in Kyoto', note: 'peak is inside your Colorado window', manual: { 1: 'part', '1B': 'part', '1C': 'part', 2: 'part', 3: 'part', 4: 'no', 5: 'part' }, why: { 1: 'eight nights spanning the turn', '1B': 'northern hills at peak, centre part-turned', '1C': 'earliest Kyoto — northern hills only', 2: 'colour building', 3: 'nine nights spanning the turn', 4: 'first colour only, early Nov', 5: 'early — the hills are turning, the city is not' } },
];

// How the choice was framed on the day it was made. Costs are each itinerary's own costTotal.
export const recommendation = [
  ['You want Kyoto plus one more place, and no stop cut short', 'Fifteen nights, 6–22 November: three at a Relais & Châteaux ryokan at 1,000m in the Alps with the Venus Line and Shinhotaka still open, and three in Hakone at its own mid-November peak instead of two. $36.2k, and one extra weekday of leave', '1B'],
  ['You want the most time in Kyoto', 'Eight nights across the turn — long enough to repeat a favourite and to lose a day to rain without it mattering. $34.8k', 1],
  ['You want to finish somewhere quiet', 'Straight past Kyoto to a seven-generation ryokan on the crab coast, in crab season. The shortest and earliest Kyoto block, so it leans on the northern hills. $34.6k', '1C'],
  ['You want the most wildlife for the money', 'Flying squirrels and two macaque troops on one rail line, crab week, and Kenrokuen at its mid-November peak — the one itinerary whose season the re-date actually suits. $31.2k', 2],
  ['It has to be the Ezo momonga specifically', 'The only route that shows you that species — but the re-date puts you in Hokkaido before the cranes gather, so it is now the squirrel alone. $30.2k', 3],
  ['Warmth, a road trip and the lowest number', 'Cheapest at $28.2k, the only all-temp-band option, and the biggest buffer before Colorado — but no Tokyo, so no sword smithing, owl café or Karuizawa squirrels', 4],
  ['Breadth over depth', 'The most places in one trip, at $37.0k, landing on a Thursday. With peak Kyoto gone and Hokkaido now visited early, it is the broad option rather than the best-at-anything one', 5],
];
