// THE FOUR BASES — where you sleep, and everything reachable from each one.
//
// Feeds bases.html and tools/basemap.mjs. The `min` values here are the same numbers the day
// sheets subtract from to derive their leave-by times, so a journey cannot be one duration on
// the map and another on the schedule.
//
// Conventions
//   name      the PLACE, not the hotel — it is what the nav, the outline and the day sheets say
//   hotel     the property you sleep in there
//   at        [lon, lat] — same order as content/geo.mjs, which some entries import directly
//   min       door-to-door minutes from that base's hotel, including the walk at both ends
//   mode      walk | metro | rail | bus | boat | ropeway | car | air
//   confirm   true = not verified from an operator page; treat as an estimate and check
//
// Sources for the numbers are in tools/RUNBOOK_SOURCES.md.

import { places } from './geo.mjs';

// ── the four bases ───────────────────────────────────────────────────
// `pois` are everything the itinerary actually visits from that base, plus the transfer points
// (airport, station) that bracket the stay. Ordered near-to-far, which is also how they read.
export const bases = [
  {
    id: 'tokyo',
    entity: 'aman-tokyo',
    name: 'Tokyo',
    hotel: 'Aman Tokyo',
    where: 'Otemachi — floors 33 to 38 of Otemachi Tower',
    dates: 'Sat 7 – Tue 10 November · 4 nights',
    at: [139.7648, 35.6866],
    checkIn: '15:00',
    checkOut: '12:00',
    checkConfirm: true,
    lede: `Otemachi is the quietest possible base for this particular week, because three of the four days leave town. It sits on top of five subway lines and is an eight-minute walk from Tokyo Station, which is where both the Ome run and the Karuizawa run start. The cost of that is distance from the nightlife districts — Nishi-Azabu is a taxi, not a walk.`,
    pois: [
      { name: 'Imperial Palace East Gardens', at: [139.7570, 35.6852], min: 10, mode: 'walk', via: 'Straight out of the tower, through Otemon gate', hours: '9:00–16:00 · closed Mondays and Fridays', why: 'The answer to the dawn-arrival problem on Saturday — free, ten minutes away, and open before the hotel room is.', days: ['Sat 7'] },
      { name: 'Tokyo Station', at: [139.7671, 35.6812], min: 8, mode: 'walk', via: 'Underground concourse the whole way if it rains', why: 'Both day trips start here.', days: ['Mon 9', 'Tue 10'] },
      { name: 'Jingu Gaien ginkgo avenue', entity: 'omotesando-ginkgo', at: [139.7175, 35.6752], min: 20, mode: 'metro', via: 'Hanzomon line to Aoyama-itchome, then 5 min on foot', hours: 'Open street, always', why: 'Green-to-yellow on these dates. They gold up around 20 November.', days: ['Sun 8'] },
      { name: 'Akiba Fukurou (owl café)', entity: 'akiba-fukurou', at: [139.7745, 35.6990], min: 20, mode: 'metro', via: 'Marunouchi line to Awajicho, 5 min on foot', hours: 'Roughly 12:00–19:00 · five slots a day', book: 'Reservation only, via select-type.com. Card charged at booking. Arrive 10 minutes early — the door is locked during the session.', days: ['Sun 8'] },
      { name: 'Meiji Jingu', entity: 'meiji-jingu', at: [139.6993, 35.6764], min: 25, mode: 'metro', via: 'Chiyoda line direct to Meiji-jingumae, then 5 min on foot', hours: 'Sunrise to sunset — about 6:20–16:20 in November', days: ['Sun 8'] },
      { name: "L'Effervescence", entity: 'leffervescence', at: [139.7205, 35.6598], min: 20, mode: 'car', via: 'Taxi to Nishi-Azabu. Thirty-plus minutes on the subway with a change, so take the cab.', hours: 'Closed Sundays and Mondays · dinner only Tue and Wed', book: 'Pocket Concierge, August–September. The personalised gluten-free menu is printed for the guest, so declare at booking.', confirm: true, days: ['Tue 10'] },
      { name: 'Hirata sword forge', entity: 'hirata-sword', at: [139.2380, 35.7880], min: 100, mode: 'rail', via: 'JR Chuo Rapid then the Ome line — about 1h25 from Tokyo Station, plus the local hop at the far end', hours: '150-minute session', book: 'Wabunka. The smiths’ calendar is irregular — ask early.', why: 'The furthest thing you do from a Tokyo base, and it is still a day trip.', days: ['Tue 10'] },
      { name: 'Picchio, Karuizawa', entity: 'picchio-musasabi', at: [138.5920, 36.3555], min: 130, mode: 'rail', via: 'Hokuriku shinkansen to Karuizawa (1h10), then the free Hoshinoya shuttle from the south exit (25 min) to Tombo-no-yu, 1 min on foot', hours: 'Tour runs 16:00–17:30 in November · check in 15 minutes early at the Visitor Center', book: 'Season ends 30 November 2026 — November slots are the last of the year.', days: ['Mon 9'] },
      { name: 'Haneda (HND)', at: [139.7798, 35.5494], min: 30, mode: 'car', via: 'Private transfer — about 25 minutes at dawn, 40 in traffic', why: 'Arrival only. You leave the country from Osaka.', days: ['Sat 7'] },
    ],
  },

  {
    id: 'nikko',
    entity: 'ritz-carlton-nikko',
    name: 'Okunikko',
    hotel: 'The Ritz-Carlton, Nikko',
    where: '2482 Chugushi — the north shore of Lake Chuzenji, 1,269m',
    dates: 'Wed 11 – Sat 14 November · 3 nights',
    at: [places.chuzenji.lon, places.chuzenji.lat],
    checkIn: '15:00',
    checkOut: '12:00',
    checkConfirm: true,
    lede: `<strong>The governing fact here is daylight, not distance.</strong> On 13 November the sun rises at 06:16 and sets at 16:36 — and every paid site in the shrine precinct is shut by 16:00, Shinkyo by 15:30. So the whole of your golden hour happens after you have been locked out of everything you paid for. The schedule that works inverts the usual one: <strong>Rinnoji opens at 08:00 and is the only World Heritage site you can enter in raking light</strong>; Toshogu opens at 09:00, not the 08:00 the older guidebooks say; and the last ninety minutes of the day belong to <strong>Kanmangafuchi and Shinkyo, which are free and never close</strong>.<br><br>The second fact is elevation. You sleep at 1,269m where the colour finished in October, and the colour you came for is six hundred metres downhill. That forty-minute bus is not a chore on this trip — it is the sightseeing. <em>Drive it rather than bus it: two hundred minutes of a ten-hour day is a lot to give away against unforgiving last-entry times.</em>`,
    pois: [
      { name: 'Futarasan Chugushi', at: [places.chuzenji.lon + 0.001, places.chuzenji.lat + 0.001], min: 5, mode: 'walk', via: 'The shrine is 2484 Chugushi; the hotel is 2482 — adjacent lot numbers', hours: '09:00–16:00 in November · open year-round · free', why: 'The best low-effort thing available from the door: a mid-mountain shrine founded in 784 at the foot of Nantai, with seven Important Cultural Properties and a thousand-year-old yew. Walk up before breakfast — frost, the lake, and the mountain catching first light, with essentially nobody there.', confirm: true , days: ['Wed 11'] },
      { name: 'Chuzenji Onsen terminal', at: [139.4869, 36.7378], min: 8, mode: 'car', why: 'The bus down the Irohazaka, and the boat pier.' , days: ['Fri 13', 'Sat 14'] },
      { name: 'Kegon Falls', entity: 'lake-chuzenji', at: [139.5033, 36.7386], min: 12, mode: 'car', via: 'Five minutes on foot from Chuzenji Onsen', hours: '08:00–17:00 to 30 November, last entry 16:40 · elevator ¥600', why: 'Ninety-seven metres, and an elevator down through the rock to the plunge pool. A free prefectural deck above it ran a light-up 15–24 November in 2025, sunset to 19:00 — worth having the concierge check the 2026 dates.', confirm: true , days: ['Wed 11', 'Fri 13'] },
      { name: 'Mount Nantai', entity: 'lake-chuzenji', at: [139.4913, 36.7654], min: 10, mode: 'walk', hours: 'Climbing season 25 April – 11 November · registration 06:00–12:00 only', warn: 'The gate is locked from the 12th, so this is off the table. The 11th is technically the last day, but you arrive that day, registration shuts at noon, and it is a seven-hour round trip against a 16:36 sunset. Do not attempt it. Worth asking whether the closing ceremony is held at Chugushi on the 11th — that would be happening 200m from your room.' , days: ['Wed 11'] },
      { name: 'Odashiro-ga-hara', at: [139.4400, 36.7810], min: 25, mode: 'car', via: 'Or the low-emission shuttle from Akanuma, 12 min', hours: 'Daylight — the shuttle runs to some point in November', why: 'The grassland with the lone white birch called the Lady of Odashiro, the most photographed tree in Nikko. A frost morning in mid-November is the classic version of that photograph.', confirm: true , days: ['Fri 13'] },
      { name: 'Nikko Botanical Garden', at: [139.5860, 36.7440], min: 35, mode: 'car', hours: '09:00–16:30, last entry 16:00 · ¥500 · closed Mondays, and the season ends 30 November', warn: 'A bear was inside the grounds twice in early August 2026 and the garden closed both times. 2026 has been a bad bear year across northern Japan — carry a bell here and at Kanmangafuchi, and read the notices the morning you go.', why: "The University of Tokyo's alpine collection, directly across the river from the Jizo. Botanical rather than colourful by now — which suits this trip better than another foliage stop would." , days: ['Thu 12'] },
      { name: 'Kanmangafuchi Abyss', entity: 'kanmangafuchi', at: [139.5906, 36.7461], min: 35, mode: 'car', via: 'Parking on site; 30 minutes on foot from Toshogu', hours: 'Free · always open', why: 'The strongest photography call in Nikko, and the only site here you can stand in at sunrise or blue hour, because it never closes and costs nothing. Seventy Jizo in red bibs above a lava gorge, past peak by a week — so the maples are on the moss and the statues rather than over them. Leeches are a June-to-October problem.' , days: ['Thu 12'] },
      { name: 'Tamozawa Imperial Villa', at: [139.5940, 36.7420], min: 35, mode: 'car', hours: '09:00–16:30, last reception 15:45 · ¥600', why: 'A hundred and six rooms of unpainted hinoki and tatami — the largest surviving wooden imperial residence in Japan, and the one garden here that peaks mid-to-late November rather than in October. Far quieter than the shrines. Allow ninety minutes.', warn: 'Normally closed Tuesdays, but it stays open every day from 15 October to 14 November, and your last day is a Sunday. Open throughout.' , days: ['Thu 12'] },
      { name: 'Rinnoji — Sanbutsudo, Taiyuin, Shoyoen', entity: 'nikko-toshogu', at: [139.5990, 36.7530], min: 40, mode: 'car', hours: '08:00–16:00 in November, last entry 15:30 · the ¥1,000 three-facility set covers all three', warn: 'The set-ticket counter closes at 13:30 in November. Buy it in the morning or you are stuck paying singles. The Treasure House and Shoyoen also close about ten days a year on unpublished dates — phone 0288-54-0531.', why: 'Opening at 08:00 makes this the only World Heritage precinct you can photograph in good light. Taiyuin is the sleeper of Nikko: a fifth of the footfall, black lacquer rather than gold, and gates climbing through deep cedar — which flatters November light instead of fighting it.' , days: ['Thu 12'] },
      { name: 'Nikko Toshogu', entity: 'nikko-toshogu', at: [139.5986, 36.7581], min: 40, mode: 'car', hours: '09:00–16:00 in November, last entry 15:30 · ¥1,600, or ¥2,400 with the Treasure Museum', warn: 'It opens at 09:00, not the 08:00 older guidebooks give. Be at the gate on the hour — the coaches are not far behind.', why: 'Ieyasu\'s mausoleum: fifty-five buildings, five hundred carvings on the Yomeimon alone, the sleeping cat, and two hundred steps up to the tomb through quiet cedar. Take the ¥800 upgrade for the Treasure Museum; skip the ¥800 Museum of Art, which bundles with nothing.' , days: ['Thu 12'] },
      { name: 'Nikko Kanaya Hotel', at: [139.5950, 36.7500], min: 38, mode: 'car', hours: 'Main Dining Room lunch 11:30–14:30 last order · reserve via TableCheck', why: 'Founded 1873 and the oldest surviving resort hotel in Japan — Einstein and Lindbergh both stayed. Classical French in the 1893 dining room, and it drops neatly into the dead middle of a shrine day between the morning light and the 15:30 cutoffs. The History House next door, a 360-year-old samurai residence, opens 09:30–16:30.', confirm: true , days: ['Thu 12'] },
      { name: 'Shinkyo Bridge', entity: 'nikko-toshogu', at: [139.5980, 36.7476], min: 38, mode: 'car', hours: '09:30–15:30 — the shortest window of anything here · ¥300 to walk on it', why: 'Do not pay. The crossing is a dead end, and every good photograph of Shinkyo is taken from outside it. Being free and unfenced makes it one of only two things in Nikko available to you at 16:30 — use it as the sunset stop on the way back up the mountain.' , days: ['Thu 12'] },
      { name: 'Tobu-Nikko / JR Nikko stations', at: [139.6180, 36.7470], min: 45, mode: 'car', via: 'The bus is 36–40 minutes downhill and ¥1,250 — the 50 minutes quoted everywhere is the uphill run', why: 'Where the 15th begins. Take the JR side: Tobu is quicker to Tokyo but lands you at Asakusa, and you then cross the city with the cases.' , days: ['Wed 11', 'Sat 14'] },
    ],
  },

  {
    id: 'shuzenji',
    entity: 'asaba-ryokan',
    name: 'Shuzenji',
    hotel: 'Asaba',
    where: 'Shuzenji Onsen, on the Katsura river — Izu peninsula, Shizuoka',
    dates: 'Sat 14 – Tue 17 November · 3 nights',
    at: [places.shuzenji.lon, places.shuzenji.lat],
    checkIn: '14:30',
    checkOut: '11:30',
    lede: `The most walkable base of the four, and the one that splits hardest in two. <strong>Everything in the old onsen town is inside ten minutes on foot</strong> — the temple, the bamboo path, all five bridges, the sutra hall — and the bamboo path is lit until 23:00 with a cut-paper projection thrown onto its round bench from 20:00, which makes the evening walk free and about forty minutes. <strong>Everything else needs the car.</strong> The wasabi terraces, the Fuji viewpoints and Joren Falls are 25 to 60 minutes away with sparse buses, which is why the rental is picked up at Mishima on the way in rather than argued about later. Check-in closes at 18:00, so the arrival day is not as elastic as it looks — and the stay is now <strong>three nights</strong>, which turns one crowded car day into two unhurried ones.`,
    pois: [
      { name: 'Tokko-no-yu', entity: 'shuzenji-onsen', at: [places.shuzenji.lon + 0.0004, places.shuzenji.lat - 0.0003], min: 2, mode: 'walk', hours: 'Free, always open, lit after dark', warn: 'Viewing only — bathing is prohibited and it is not a foot bath either. It lost its legal status as a bathhouse. The actual free foot baths are Kawara-yu and Sugi-no-yu on the opposite bank.' , days: ['Sun 15'] },
      { name: 'Chikurin no Komichi (bamboo path)', entity: 'shuzenji-onsen', at: [places.shuzenji.lon + 0.0009, places.shuzenji.lat - 0.0006], min: 3, mode: 'walk', via: "Effectively Asaba's back garden", hours: 'Free · 60 lamps, sunset to 23:00, year-round', why: 'The best free thing in town after dinner. From 20:00 a cut-paper projection by Mizuguchi Chiharu, born here, is thrown onto the circular bamboo bench at its centre.' , days: ['Sun 15'] },
      { name: 'Shuzen-ji temple', entity: 'shuzenji-onsen', at: [places.shuzenji.lon + 0.0016, places.shuzenji.lat + 0.0009], min: 4, mode: 'walk', hours: 'Grounds 05:00–17:00, free · Treasure Hall 08:30–16:00 in November, ¥300', why: 'Sōtō Zen, traditionally founded by Kūkai in 807. Minamoto no Yoriie was assassinated here in 1204, and the Treasure Hall holds the masks from the Noh play about it — the same play the stage at Asaba is named for.', confirm: true , days: ['Mon 16'] },
      { name: 'The five red bridges', entity: 'shuzenji-onsen', at: [places.shuzenji.lon + 0.0012, places.shuzenji.lat - 0.0011], min: 5, mode: 'walk', hours: 'Free, always open — the full circuit is a 20–30 minute stroll', why: 'Togetsu, Kokei, Katsura, Kaede and Takishita. Cross all five making a wish and your love is fulfilled; each hides a carved granite crest. It overlaps entirely with the bamboo-path walk, so do it as one loop.' , days: ['Sun 15'] },
      { name: 'Shigetsuden', entity: 'shuzenji-onsen', at: [places.shuzenji.lon + 0.0021, places.shuzenji.lat + 0.0004], min: 6, mode: 'walk', via: 'Across the river from the temple, up a short flight of steps', hours: 'Free, no closing day', why: 'The oldest wooden building in Izu — a sutra hall built by Hōjō Masako for her murdered son. The sleeper of the town.' , days: ['Mon 16'] },
      { name: 'Shuzenji Washi — Kamiya Washi Kōbō', at: [places.shuzenji.lon + 0.004, places.shuzenji.lat + 0.003], min: 8, mode: 'car', hours: '90 minutes, private', book: '¥15,000 per person for the English-language plan, interpretation included; ¥10,000 in Japanese. Minimum two people. Book at least a day ahead via shuzenjiwashi.com. Which weekdays it runs in November is unconfirmed — email first.', why: 'A thousand-year-old local paper tradition, revived, using the same spring water as the baths. The finished sheets are posted on about a week later, so it needs a shipping address.', confirm: true , days: ['Mon 16'] },
      { name: 'Shuzenji Station', at: [places.shuzenji.lon + 0.012, places.shuzenji.lat - 0.008], min: 7, mode: 'car', via: 'Taxi — Asaba runs no shuttle', why: 'The Sunzu line to Mishima, and the Odoriko straight through to Tokyo.' , days: ['Sat 14', 'Tue 17'] },
      { name: 'Izu Panorama Park', at: [138.933, 35.016], min: 22, mode: 'car', via: 'Or two stops on the Sunzu line to Izunagaoka, then a bus', hours: '09:00–17:00 in November · ¥1,800 return', why: 'A 1,791m ropeway to a 452m terrace with Fuji across Suruga Bay and reflecting pools staging an inverted one. The easiest Fuji of the trip.', confirm: true , days: ['Sun 15'] },
      { name: 'Darumayama Kōgen', at: [138.900, 34.985], min: 25, mode: 'car', hours: 'The viewpoint and car park are always open; the resthouse hours are unpublished', why: 'One of the three great views of Izu, free, and the best Fuji photograph within half an hour of the inn. Go at sunrise. Buses are sparse enough that the tourism board itself warns about them.', confirm: true , days: ['Sun 15'] },
      { name: 'Wasabi no Ōmiya', at: [138.955, 34.905], min: 30, mode: 'car', hours: '09:00–16:00 · closed Wednesdays — fine on both your days', book: 'Field walk is free and needs no reservation. The wasabi-zuke making session is ¥1,650 a head, about 40 minutes, minimum two, by phone on 0558-83-2900.', why: "A working farmer's tatami-ishi field you can walk into. Harvesting is May–July only, but the pickling runs January to November.", confirm: true , days: ['Sun 15'] },
      { name: 'Joren Falls', at: [138.936, 34.879], min: 30, mode: 'car', hours: 'Falls, car park and toilets free and always open · 200 steps down', warn: 'The visitor centre closes Tuesdays, so on the 17th there is no wasabi soft-serve and no restaurant — the waterfall itself is unaffected.', why: 'A 25m fall in a basalt gorge, and tatami-ishi wasabi terraces visible free from the observation deck.' , days: ['Sun 15'] },
      { name: 'Ikadaba wasabi terraces', at: [138.968, 34.895], min: 35, mode: 'car', hours: 'Free, always open', warn: 'Private land. Viewing is tolerated from the road only, and the tourism board warns the lane in is narrow and awkward for drivers who do not know it.', why: 'Fifteen hectares and about 1,500 terraced paddies — the largest tatami-ishi landscape in Japan, and the reason Shizuoka water wasabi is a UNESCO-recognised agricultural heritage system.', confirm: true , days: ['Sun 15'] },
      { name: 'Shuzenji Niji-no-Sato', at: [138.917, 34.958], min: 15, mode: 'car', hours: 'Day park 10:00–16:00 in November, ¥1,220 · momiji light-up 16:00–21:00, evening ticket ¥1,000', warn: 'Closed Tuesdays — except in peak season, and the light-up period counts as peak season. Nobody will confirm this in writing. Phone 0558-72-7111 before building the 17th on it.', why: 'The 2025 light-up ran 15 November to 14 December. If 2026 repeats, you arrive on opening night.', confirm: true , days: ['Sun 15', 'Mon 16'] },
      { name: 'Mishima Station', at: [places.mishima.lon, places.mishima.lat], min: 45, mode: 'car', via: 'Or 35 minutes on the Sunzu line from Shuzenji station, ¥550', why: 'Where the car comes from and goes back to, and where the Hikari to Kyoto leaves from.' , days: ['Sat 14', 'Tue 17'] },
      { name: 'Koibito-misaki, Toi', at: [138.783, 34.905], min: 55, mode: 'car', via: 'Over the Nishi-Izu Skyline and the Toi pass', hours: '09:00–17:00, free, year-round', why: 'A 180° panorama of Fuji across Suruga Bay from a cape on the west coast. Pairs with Darumayama into one long car day, timed so the return is at sunset.', confirm: true , days: ['Sun 15'] },
    ],
  },

  {
    id: 'kyoto',
    entity: 'hotel-the-mitsui-kyoto',
    name: 'Kyoto',
    hotel: 'HOTEL THE MITSUI KYOTO',
    where: 'Nakagyo-ku — Aburanokoji at Nijo, facing the castle',
    dates: 'Tue 17 – Sun 22 November · 5 nights',
    at: [135.752, 35.012],
    checkIn: '15:00',
    checkOut: '12:00',
    lede: `<strong>This base moved three kilometres west, and that single fact reshapes the week.</strong> The old one was in Gion, where both marquee dinners, the kintsugi and the Kodai-ji illumination were all a five-minute walk from bed. From here they are half an hour by subway or a fifteen-minute taxi. What you get back is everything on the other side of the compass: <strong>Nijo Castle is across the street</strong>, Takao is forty minutes better, Arashiyama is fifteen, Kyoto Station is closer than it was from Gion, and two Michelin restaurants are inside a ten-minute walk. The hinge is <strong>Nijojo-mae, three minutes away on the Tozai line</strong> — which is really the Higashiyama subway: Sanjo Keihan in five minutes, Higashiyama in seven, Keage in nine, no transfers. And after three cold mountain days in a row, the hot spring in the basement is a better recovery base than a machiya was.`,
    pois: [
      { name: 'Nijojo-mae Station', at: [135.7515, 35.0117], min: 3, mode: 'walk', via: 'Exit 2, 150m', why: 'The Tozai line. Everything in Higashiyama is one seat from here.' , days: ['Tue 17'] },
      { name: 'Nijo Castle', at: [135.7481, 35.0142], min: 6, mode: 'walk', via: 'Via Oike and Horikawa', hours: 'The autumn evening event ran 31 Oct – 7 Dec in 2025, 18:00–22:00, last entry 21:00 · ¥2,000 weekdays, ¥2,400 weekends', why: 'A whole evening with no travel at all, thirty seconds from the door. It is a projection-mapping installation rather than a classical light-up, but Seiryū-en, where the castle\'s own colour peaks, is lit as part of it.', confirm: true , days: ['Tue 17'] },
      { name: 'Nijojo Furuta', at: [135.7495, 35.0128], min: 7, mode: 'walk', hours: 'Lunch from 12:00, dinner from 17:00 · irregular closing days', book: 'Reservation only, via TableCheck or +81 75-254-8377. ¥22,000 or ¥27,500 plus service.', why: 'One Michelin star, charcoal-grilled, seven minutes on foot. The best argument for a night that involves no transport at all.', confirm: true , days: ['Wed 18'] },
      { name: 'Kamanza Nagashima', at: [135.7530, 35.0110], min: 11, mode: 'walk', hours: 'Dinner only, one party per evening', book: 'Phone only — +81 75-241-3770. The restaurant takes no online bookings.', why: 'A kappo run by a husband and wife who cook for one table a night. Michelin-listed; it appears to have lost its star in the 2026 guide.', confirm: true , days: ['Wed 18'] },
      { name: 'Nishiki Market', at: [135.7648, 35.0050], min: 20, mode: 'walk', via: '1.4 km on foot, or two subway minutes to Karasuma Oike and walk' , days: ['Sun 22'] },
      { name: 'Kyoto Station', at: [135.7585, 34.9858], min: 21, mode: 'rail', via: 'Tozai to Karasuma Oike, change, Karasuma line down — all rail, no bus. Taxi is about 15 minutes.', why: 'The Haruka on the last morning. Closer than it was from Gion.' , days: ['Wed 18', 'Sun 22'] },
      { name: 'Demachiyanagi Station', at: [135.7730, 35.0300], min: 19, mode: 'rail', via: 'Tozai to Sanjo Keihan, 4 min walk, then two stops on the Keihan Oto line', why: 'Ohara, Rurikoin and Kurama all still start here.' , days: ['Thu 19', 'Sat 21'] },
      { name: 'Gion (Hanamikoji)', entity: 'gion', at: [135.7752, 35.0037], min: 20, mode: 'rail', via: 'Tozai to Sanjo Keihan, then 11 minutes south on foot', warn: 'This was three minutes from the old hotel. The wander-out-after-dinner texture of Gion now has to be scheduled rather than absorbed.' , days: ['Tue 17'] },
      { name: 'Eikandō Zenrin-ji', entity: 'eikando', at: [135.7947, 35.0142], min: 28, mode: 'rail', via: 'Tozai straight to Keage — nine minutes, no transfer — then 13 min on foot past Nanzen-ji', hours: 'The 2025 light-up ran 15 Nov – 10 Dec, 17:30 to a 20:30 last entry · ¥700', why: 'One of the few things the move made easier.', confirm: true , days: ['Fri 20'] },
      { name: 'Kikunoi Honten', entity: 'kikunoi-honten', at: [135.7800, 34.9985], min: 30, mode: 'car', via: 'Take the taxi — 15 to 20 minutes. The subway version is Higashiyama plus a 19-minute walk.', hours: 'Dinner seatings 17:00–19:30', book: 'No online form exists. Phone +81 75-561-0015 or honten@kikunoi.co.jp, or have the hotel concierge do it — a three-Key hotel will have the relationship.', warn: 'Closed the 1st and 3rd Tuesday — 3 and 17 November 2026. The 17th is your arrival day, so this can never move earlier in the week.' , days: ['Thu 19'] },
      { name: 'Heki kintsugi — Akagane Resort 1925', entity: 'heki-kintsugi', at: [135.7797, 34.9990], min: 30, mode: 'car', hours: '120 minutes, private', book: 'Wabunka. The real-gold finish is a paid upgrade — decide at booking.', why: 'It is on Shimogawara-dori, the same street as Kikunoi — which is why the two now belong on the same day.' , days: ['Fri 20'] },
      { name: 'Kodai-ji', entity: 'kodaiji', at: [135.7813, 34.9998], min: 30, mode: 'car', hours: 'The 2025 illumination ran 24 Oct – 14 Dec, lit from 17:00, last admission 21:30 · ¥600', warn: 'Book the hotel car for this. It is the Saturday of a three-day holiday weekend at foliage peak, and Higashiyama taxis will not be hailable on the street.', confirm: true , days: ['Sat 21'] },
      { name: 'Kodaiji Jugyuan', entity: 'kodaiji-jugyuan', at: [135.7805, 35.0003], min: 30, mode: 'car', book: 'Book late August–early September for Saturday 21 November.', why: 'The farewell dinner, next door to the illumination. Still perfectly adjacent once you are there — it is only getting there that changed.' , days: ['Sat 21'] },
      { name: 'Arashiyama & Iwatayama', entity: 'arashiyama-monkeys', at: [135.6773, 35.0122], min: 42, mode: 'rail', via: 'Tozai one stop to Nijo, then the JR Sagano line straight to Saga-Arashiyama', hours: 'Monkey park 9:00–16:30, last entry 16:00, plus a 20-minute climb', why: 'Fifteen minutes better than it was from Gion.' , days: ['Fri 20'] },
      { name: 'Takao — Jingo-ji and Kozan-ji', entity: 'takao', at: [135.6725, 35.0570], min: 43, mode: 'bus', via: 'Tozai six minutes west to Uzumasa Tenjingawa, then City Bus 8 — which skips the Kyoto Station scrum entirely', hours: 'Jingo-ji 9:00–16:00 · Kozan-ji 8:30–17:00', why: 'Thirty to forty minutes better each way than the old routing. Buy the ¥1,100 Subway & Bus 1-Day Pass — it covers the whole day, and the bus-only pass no longer exists.', warn: 'Jingo-ji is about 400 steps up from the river.' , days: ['Wed 18'] },
      { name: 'Rurikoin', entity: 'rurikoin', at: [135.8010, 35.0715], min: 40, mode: 'rail', via: 'To Demachiyanagi, then the Eizan line to Yase-Hieizanguchi', hours: '10:00–17:00 · last entry 16:30 · ¥2,000', book: 'The 2026 autumn season is announced as 1 October – 13 December, reservation required through the peak window. Book the moment the form opens.' , days: ['Thu 19'] },
      { name: 'Kurama & Kibune', entity: 'kurama-kibune', at: [135.7630, 35.1230], min: 52, mode: 'rail', via: 'To Demachiyanagi, then 30 minutes on the Eizan line through the maple tunnel', warn: 'The Eizan is a two-car railway that has left passengers standing on platforms in ordinary autumn conditions, and Saturday the 21st is day one of a three-day national holiday. Go at opening or not at all, and do not approach Kibune by car.' , days: ['Sat 21'] },
      { name: 'Sanzen-in, Ohara', entity: 'sanzen-in-ohara', at: [135.8345, 35.1190], min: 52, mode: 'bus', via: 'Karasuma line to Kokusaikaikan, then Kyoto bus 19', hours: '8:30–17:00 in November · last entry 16:30', why: 'Unchanged by the move. And the hotel\'s own 1703 gate was built for the court attached to this temple — you sleep behind it and then go and see where it came from.' , days: ['Thu 19'] },
      { name: 'Kansai (KIX)', at: [135.2441, 34.4347], min: 100, mode: 'rail', via: 'Rail or taxi to Kyoto Station, then the Haruka, about 75–80 minutes', warn: 'Sunday 22 November is the middle day of a three-day weekend. Reserve Haruka seats rather than walking up.' , days: ['Sun 22'] },
    ],
  },
];
