// The five itineraries, transcribed from Itinerary Designs.md.
// `ref` arrays attach entities (and therefore photos) to individual days.

export const shared = {
  dateLogic: `Kyoto's 2026 foliage is forecast to peak <strong>Nov 25 – Dec 7</strong>, densest Nov 29 – Dec 3 — later than average. So itineraries wanting peak Kyoto should end as late as possible, with Kyoto last. Kenrokuen in Kanazawa peaks mid-November; the Japan Alps peaked in mid-October and Kamikochi closes Nov 15, so it is excluded; Kyushu runs early to late November; Hokkaido's foliage is already over — there it is pre-winter wildlife season instead. Crane feeding at Tsurui starts mid-to-late November; Ezo momonga are viewable year-round with a guide. Kyoto crowds are worst Nov 15–25, including the Nov 21–23 holiday weekend; the Nov 29 – Dec 3 tail has peak colour with the crowd wave passing.`,

  flights: {
    title: 'Flights from SFO',
    sub: '≈ $9,000 – $11,000 per couple, business, round trip',
    points: [
      `<strong>Best product: ANA "The Room"</strong> on SFO→HND — a 28-inch-wide lie-flat with a closing door. SFO frequencies alternate between the new and old configurations, so <strong>verify the seat map before ticketing</strong>. About $4,500–5,500 per person booked 3–6 months out.`,
      `<strong>Open-jaw into Tokyo, out of Osaka.</strong> Itineraries 1, 3 and 4 end near Kyoto. United is the only SFO–KIX nonstop, and a single United multi-city ticket (SFO→HND / KIX→SFO, Polaris) prices within about $0–500 of a normal round trip. It saves a half-day backtrack to Tokyo.`,
      `JAL from SFO still flies its older Sky Suite — the new A350 suite is not on SFO yet. Consolidator fares run $3,400–4,800 round trip if you want to shave $2,000.`,
      `Depart SFO Saturday morning, land in Japan Sunday afternoon. Return flights land at SFO the same day they leave Japan, so a Sunday departure from Japan is a Sunday arrival home.`,
    ],
  },

  transportTable: {
    title: 'Rail vs self-drive — the honest trade-offs',
    rows: [
      ['Comfort', 'Shinkansen Green/Gran Class ≈ domestic first class; 2h15 Tokyo–Kyoto', 'Lexus NX/RX rents officially from Toyota Rent a Car ($230–410/day); roads are excellent'],
      ['Freedom', 'Fixed but very frequent departures', 'Wins in rural areas — stop anywhere'],
      ['Luggage', 'The real catch: big bags need reserved oversize space. Solution — <strong>takkyubin</strong> forwarding, $15–22/bag, next-day hotel to hotel; travel with overnight bags', 'The trunk swallows everything'],
      ['Cities', 'Wins outright', 'Tokyo/Kyoto parking $50–90/day, foliage gridlock, narrow one-ways — a burden'],
      ['Safety / stress', 'Zero', 'Left-side driving; IDP required (<strong>1949 Geneva booklet from AAA, ~$20</strong> — card versions rejected); Hokkaido in late Nov means black ice, 4pm sunsets, studless tyres (fitted free on all Hokkaido rentals)'],
      ['Verdict', '<strong>Cities and trunk routes</strong>', '<strong>Rural loops: eastern Hokkaido (essentially car-only), Kyushu onsen country, Yakushima</strong>'],
    ],
    note: `The hybrid pattern — rail or fly between hubs, rent for 2–4 day rural loops, takkyubin the bags past the loop — appears in itineraries 2, 3 and 4. Private Alphard day-hire in Kyoto or Tokyo ($300–500/day) is the no-stress option for temple-hopping days.`,
  },

  glutenFree: {
    title: 'The gluten-free playbook',
    sub: 'For Ashly. This drives more of the restaurant selection than the star counts do.',
    points: [
      `<strong>Kikunoi Honten has a formal gluten-free intake</strong> on its reservation form. Declare it there — no same-day dietary requests. <strong>L'Effervescence</strong> prints a personalised GF menu. <strong>Sézanne explicitly refuses gluten-free — avoid it.</strong> Monk is pizza-centric — skip.`,
      `<strong>Gora Kadan</strong> has celiac guest reviews confirming full gluten-free kaiseki and breakfast, for staying guests only. Beniya Mukayu, Asaba and Sankara Yakushima all accommodate with advance notice; <strong>Sankara publishes its gluten-free options outright</strong>.`,
      `Tactics: tamari instead of shoyu (request at booking, carry travel packets), yakitori shio not tare, teppanyaki salt-grilled, sushi minus nikiri and marinated pieces. Never tempura, ramen, udon or unagi. Carry a Japanese-language celiac card (Legal Nomads).`,
      `Backup restaurants: Gluten Free T's Kitchen in Tokyo (certified GF — they even do GF tempura) and Little Bird in Kyoto.`,
      `Send every ryokan and restaurant the gluten-free brief 4–6 weeks ahead. <strong>A detailed reply is the signal that the kitchen can be trusted</strong> — a vague one is a warning.`,
    ],
  },

  costModel: `Per-couple estimates: business flights $9–11k; ryokan rates include kaiseki dinner and breakfast; city hotels are room and breakfast only; the dining line covers all meals not included in hotels, with marquee dinners at $250–900 per couple each; experiences are priced from operator pages. A 5–8% buffer is <em>not</em> included. FX at ¥150/$.`,

  bookNow: {
    title: 'Book-now list',
    sub: 'For a November 2026 trip, acting in July–September 2026',
    groups: [
      ['Now', 'Kyoto hotels for late November (peak rooms go 9–12+ weeks out; Tawaraya and Aman-class 9–12 months). Gora Kadan. Hinanoza. Sankara. Beniya Mukayu. Flights — with the ANA seat-map check.'],
      ['Aug – early Sep', 'Kikunoi Honten via Tableall or My Concierge, declaring GF in the form. L\'Effervescence via Pocket Concierge. Zeniya (zeniya.co.jp — not the .info domain). Wabunka modules for the Hirata sword and the Heki kintsugi — the Hirata calendar is irregular, so ask early.'],
      ['Fixed windows', '<strong>Picchio\'s flying squirrel tour — the season ends 30 November 2026, so late November is its closing week and the last slots go first.</strong> Akiba Fukurou, the owl café — reservation only, and the price only appears at checkout. Goh — email exactly 60 days out. Kyudo studio — email to confirm location and dates.'],
      ['4–6 weeks out', 'Gluten-free briefs to every kitchen (celiac-specific, tamari request, fryer question). Takkyubin plan. AAA 1949-format IDP if driving.'],
    ],
  },
};

export const itineraries = [
  // ══════════════════════════════════════════════════════════════ 1 ══
  {
    num: 1,
    slug: 'peak-momiji-classic',
    title: 'Peak Momiji Classic',
    tagline: 'The seeds trip — now with three wildlife days and $2,100 off',
    dates: 'Sat Nov 14 → Sun Nov 29, 2026',
    length: '15 nights',
    route: ['Tokyo · 4n', 'Hakone · 2n', 'Kyoto · 7n'],
    routeNote: 'Open-jaw, returning from KIX',
    cost: '$34,100',
    costBand: '$32–34k',
    temp: '45–65°F',
    tempStatus: 'good',
    bestFor: 'Peak foliage, Gora Kadan, and both seed restaurants',
    transport: {
      mode: 'Rail',
      text: `This route never leaves the shinkansen spine — a car would sit in $70/day parking through peak-season gridlock. Green Car booked via the smartEX app; takkyubin the bags Tokyo→Kyoto past the Hakone stop; private transfers on arrival and departure days.`,
      ref: ['shinkansen-green-car', 'ana-the-room'],
    },
    hero: 'eikando',
    heroCard: ['gora-kadan', 'tofukuji', 'hirata-sword'],
    pitch: `Still the trip your seeds describe most literally — Gora Kadan, Kikunoi, Jugyuan, sword smithing, the deep kintsugi, kyudo — with a full seven nights in Kyoto arriving at the forecast foliage peak. Trimming the workshops did two things: it took $4,000 off the number, and it opened four days that are now the best wildlife in the plan outside Hokkaido. Flying squirrels at Karuizawa on the Wednesday, the Nara deer on the holiday Monday, the Iwatayama macaques above Arashiyama, and an owl café on the first Tokyo afternoon.`,
    days: [
      { date: 'Sat 14', where: '✈', text: 'SFO→HND, ANA The Room', ref: ['ana-the-room'] },
      { date: 'Sun 15', where: 'Tokyo', text: 'Land, private transfer, gentle evening. <strong>Palace Hotel Tokyo</strong>.', ref: ['palace-hotel-tokyo'] },
      { date: 'Mon 16', where: 'Tokyo', text: 'Meiji Jingu and the Jingu Gaien ginkgo, which are turning gold. Afternoon: <strong>Akiba Fukurou</strong>, the owl café — reservation only, so book it now. <strong>L\'Effervescence</strong> dinner — 3★, printed GF menu, ≈ $1,200/couple.', ref: ['meiji-jingu', 'omotesando-ginkgo', 'akiba-fukurou', 'leffervescence'] },
      { date: 'Tue 17', where: 'Tokyo · Ome', text: '<strong>Hirata sword smithing</strong> — forge a small katana with the husband-and-wife smiths, engraved and shipped home. 150 min, ≈ $1,700/couple. The exact experience from the seeds.', ref: ['hirata-sword'] },
      { date: 'Wed 18', where: 'Karuizawa', text: '<strong>Flying squirrels.</strong> Shinkansen out after lunch (1h10), then Picchio\'s <strong>musasabi watching tour</strong> — a nest camera, then the animal leaving the hole at dusk to glide. 16:00–17:30 in November; back in Tokyo by about 19:15. Better than 90% success. <em>Book early: the season closes 30 November.</em>', ref: ['picchio-musasabi', 'gran-class'] },
      { date: 'Thu 19', where: 'Hakone', text: 'Romancecar or private transfer. <strong>Gora Kadan</strong> — in-room gluten-free kaiseki, cypress onsen.', ref: ['gora-kadan'] },
      { date: 'Fri 20', where: 'Hakone', text: 'Open-Air Museum, Lake Ashi — foliage peaks here mid-November. Lunch at <strong>Itoh Dining by Nobu</strong> (teppanyaki, a GF-safe format). Second kaiseki at the ryokan.', ref: ['hakone-open-air-museum', 'lake-ashi', 'itoh-dining-nobu'] },
      { date: 'Sat 21', where: 'Kyoto', text: 'Green Car Odawara→Kyoto. Check in to <strong>Sowaka</strong> in Gion (or Hotel The Mitsui, +$1–3k/night). Evening Gion walk.', ref: ['sowaka', 'gion'] },
      { date: 'Sun 22', where: 'Kyoto', text: 'Early — 8am — Honen-in and the Philosopher\'s Path before the crowds. <strong>Kodaiji Jugyuan</strong> dinner (2★, from the seeds) — literally next door to Kodai-ji\'s night illumination.', ref: ['philosophers-path', 'kodaiji-jugyuan', 'kodaiji'] },
      { date: 'Mon 23', where: 'Nara', text: '<em>Public holiday — leave the city.</em> <strong>Nara</strong>: a thousand sika deer loose among the temples, Todai-ji\'s Great Buddha hall, and the stone lantern avenue at Kasuga Taisha. 45 minutes each way, and the best wildlife photography on the Kansai side. <em>Alternative if you would rather have tea country: Uji and Byodo-in.</em>', ref: ['nara-deer', 'byodo-in-uji'] },
      { date: 'Tue 24', where: 'Kyoto', text: '<strong>Traditional kintsugi with Mio Heki</strong> at a Higashiyama villa (120 min, ≈ $600/couple, real-gold option) — the one craft workshop you kept, and the deep version. Eikando illumination in the evening.', ref: ['heki-kintsugi', 'eikando'] },
      { date: 'Wed 25', where: 'Kyoto · Arashiyama', text: 'A full day west. <strong>Iwatayama monkey park</strong> at opening — 120 wild macaques on a hilltop with Kyoto spread out behind them — then the bamboo grove, Tenryu-ji\'s garden and the Hozugawa in colour, all before the afternoon crowds thicken.', ref: ['arashiyama-monkeys', 'arashiyama'] },
      { date: 'Thu 26', where: 'Kyoto', text: '<strong>Kikunoi Honten</strong> (3★, formal GF process — book Aug/Sep, ≈ $900–1,100/couple). Morning <strong>kyudo</strong> session (≈ $270/couple; confirm the studio location by email).', ref: ['kikunoi-honten', 'kyudo'] },
      { date: 'Fri 27', where: 'Kyoto · Ohara', text: 'Ohara at peak colour: <strong>Sanzen-in</strong> and its moss garden of jizo figures, forty minutes north and dramatically less crowded than the city. <strong>Rurikoin</strong> on the way back if you reserved it.', ref: ['sanzen-in-ohara', 'rurikoin'] },
      { date: 'Sat 28', where: 'Kyoto', text: 'Free day at the forecast peak. Tofuku-ji early, Rurikoin (reserve ahead), farewell dinner at <strong>Cenci</strong> (Italian 1★, easy GF, ≈ $350/couple).', ref: ['tofukuji', 'rurikoin', 'cenci-kyoto'] },
      { date: 'Sun 29', where: '✈', text: 'KIX→SFO Polaris, landing Sunday.', ref: [] },
    ],
    stays: ['palace-hotel-tokyo', 'gora-kadan', 'sowaka'],
    altStays: ['hotel-the-mitsui-kyoto', 'gora-byakudan'],
    dining: ['leffervescence', 'kikunoi-honten', 'kodaiji-jugyuan', 'cenci-kyoto', 'itoh-dining-nobu'],
    doing: ['hirata-sword', 'picchio-musasabi', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['eikando', 'tofukuji', 'kodaiji', 'philosophers-path', 'arashiyama', 'nara-deer', 'rurikoin', 'sanzen-in-ohara', 'byodo-in-uji', 'gion', 'lake-ashi', 'hakone-open-air-museum', 'meiji-jingu', 'omotesando-ginkgo', 'yanaka-tokyo'],
    costRows: [
      ['Flights (open-jaw business)', '$9,500'],
      ['Hotels — Palace 4n + Gora Kadan 2n (HB) + Sowaka 7n', '$16,300'],
      ['Dining (the two ryokan kaiseki nights are already included above)', '$4,200'],
      ['Experiences — sword $1,700, Heki kintsugi $600, kyudo $270, Karuizawa flying squirrels $170, owl café $60, monkey park $10', '$2,810'],
      ['Ground — Green Car, transfers, takkyubin', '$1,300'],
    ],
    costTotal: '≈ $34,100',
    levers: `<strong>Now within about $3k of budget without touching the hotels.</strong> The remaining levers: United or consolidator fares (−$2,000) and Gora Byakudan instead of Gora Kadan (−$1,300) would land it near $30,800. Going the other way, Kyoto at Hotel The Mitsui instead of Sowaka still adds $7,000–20,000.`,
    verdict: `<strong>The cuts did more here than anywhere else.</strong> Dropping the matcha, the indigo and two of the three ceramics workshops took $4,000 out of the activity line, and cutting the $2,600 matcha in particular fixed a real error: the original plan's "$4,900 experiences" line didn't add up to its own itemised prices, which understated this trip by about $1,900. The corrected figure is above. What replaced them costs $240 and adds three separate wildlife opportunities. <strong>Book the Kyoto hotels, Kikunoi and the Picchio tour immediately</strong> — peak rooms sell 12 weeks out and the flying-squirrel season closes 30 November.`,
    verdictTone: 'good',
  },

  // ══════════════════════════════════════════════════════════════ 2 ══
  {
    num: 2,
    slug: 'crafts-crab-snow-monkeys',
    title: 'Crafts, Crab & Snow Monkeys',
    tagline: 'Two wildlife days on one rail line, crab week, and Kenrokuen at peak',
    dates: 'Sat Nov 7 → Sun Nov 22, 2026',
    length: '15 nights',
    route: ['Tokyo · 3n', 'Shibu Onsen · 2n', 'Kanazawa/Kaga · 3n', 'Kyoto · 5n'],
    routeNote: 'Out of KIX',
    cost: '$29,700',
    costBand: '$29–30k',
    temp: 'Mostly good; Nagano in the 40s',
    tempStatus: 'ok',
    bestFor: 'Wildlife, crab season, Kenrokuen at peak',
    transport: {
      mode: 'Rail + one car day',
      text: `The Hokuriku shinkansen's <strong>Gran Class</strong> — attendant service, about $190 for the Tokyo→Kanazawa leg — is the best train seat in the country and exists only on this line. The route is partly built around it. The local Nagaden line plus a taxi covers the monkey park; no rental needed.`,
      ref: ['gran-class', 'shinkansen-green-car'],
    },
    hero: 'kenrokuen',
    heroCard: ['snow-monkeys', 'zeniya-kanazawa', 'beniya-mukayu'],
    pitch: `Four regions, the best train seat in Japan, and a set of alignments that only work in this exact fortnight: Kenrokuen at its mid-November peak and snow crab season opening the week before you arrive. Trimming the craft workshops changed what this trip is about — it used to be the densest craft run of the five, and now its real distinction is wildlife. The Hokuriku line happens to thread both Karuizawa and Nagano, so the flying squirrels and the snow monkeys sit two days apart on the same rails. The trade is Kyoto — you arrive Nov 17–22, colour building but likely just before the forecast peak, in exchange for rooms about $300/night cheaper.`,
    days: [
      { date: 'Sat 7', where: '✈', text: 'SFO→HND', ref: ['ana-the-room'] },
      { date: 'Sun 8', where: 'Tokyo', text: 'Land. <strong>Palace Hotel Tokyo</strong>.', ref: ['palace-hotel-tokyo'] },
      { date: 'Mon 9', where: 'Tokyo · Ome', text: '<strong>Hirata sword smithing</strong> in the morning out west. <strong>L\'Effervescence</strong> dinner with its printed GF menu.', ref: ['hirata-sword', 'leffervescence'] },
      { date: 'Tue 10', where: 'Karuizawa', text: '<strong>Akiba Fukurou</strong>, the owl café, in the morning — then the shinkansen to Karuizawa for Picchio\'s <strong>musasabi watching tour</strong>: a camera inside the nest, then the animal leaving at dusk to glide. 16:00–17:30, back in Tokyo by about 19:15. <em>Season closes 30 November.</em>', ref: ['akiba-fukurou', 'picchio-musasabi'] },
      { date: 'Wed 11', where: 'Nagano', text: 'Gran Class Tokyo→Nagano (1h20) — back out along the same line, through Karuizawa. Zenko-ji. On to <strong>Kokuya</strong> in Shibu Onsen, a 400-year-old ryokan with the master key to the town\'s nine bathhouses.', ref: ['gran-class', 'zenkoji', 'kokuya'] },
      { date: 'Thu 12', where: 'Jigokudani', text: '<strong>Snow monkey day.</strong> <em>Expectation set: the park is open and the monkeys are present and active, but they rarely soak before real cold — you may get a dusting of snow, not the steaming-bath postcard. That is December to February.</em>', ref: ['snow-monkeys'] },
      { date: 'Fri 13', where: 'Kanazawa', text: 'Gran Class Nagano→Kanazawa (1h10). Higashi Chaya and the gold-leaf district. Hyatt Centric or similar.', ref: ['higashi-chaya', 'hyatt-centric-kanazawa'] },
      { date: 'Sat 14', where: 'Kanazawa', text: 'Kenrokuen at its <strong>mid-November peak</strong>, plus the evening illumination. <strong>Zeniya</strong> dinner — 2★ Relais & Châteaux kaiseki with no fixed menu, so the chef tailors per guest, which is the best GF signal in the city. <strong>Crab season opened Nov 6</strong>, and kano-gani is naturally gluten-free.', ref: ['kenrokuen', 'zeniya-kanazawa'] },
      { date: 'Sun 15', where: 'Kaga', text: 'Local train to Yamashiro Onsen. <strong>Beniya Mukayu</strong> — Relais & Châteaux, gluten-free kaiseki with notice, private onsen.', ref: ['beniya-mukayu'] },
      { date: 'Mon 16', where: 'Kaga', text: 'Second Mukayu night, deliberately empty: morning yoga, the library, the private rotenburo. The Kutani ware and Kaga yuzen workshops nearby are dropped along with the other craft modules — this is the day the trip stops moving.', ref: ['beniya-mukayu'] },
      { date: 'Tue 17', where: 'Kyoto', text: 'Thunderbird express, about 2 hours. <strong>Sowaka</strong>, at pre-peak rates.', ref: ['sowaka'] },
      { date: 'Wed 18', where: 'Kyoto', text: '<strong>Kikunoi Honten</strong> dinner. Early morning on the Philosopher\'s Path.', ref: ['kikunoi-honten', 'philosophers-path'] },
      { date: 'Thu 19', where: 'Kyoto · Arashiyama', text: '<strong>Iwatayama monkey park</strong> at opening — wild macaques on the hilltop with the city behind them — then the bamboo grove and Tenryu-ji, with Arashiyama\'s colour building.', ref: ['arashiyama-monkeys', 'arashiyama'] },
      { date: 'Fri 20', where: 'Kyoto · Ohara', text: 'Ohara: <strong>Sanzen-in</strong>, the moss garden and the jizo figures, forty minutes north of the city and far quieter than it.', ref: ['sanzen-in-ohara'] },
      { date: 'Sat 21', where: 'Kyoto', text: '<strong>Heki kintsugi</strong> — the one craft workshop kept — and <strong>kyudo</strong> if you want the morning filled. <strong>Kodaiji Jugyuan</strong> farewell dinner plus the illumination next door.', ref: ['heki-kintsugi', 'kyudo', 'kodaiji-jugyuan', 'kodaiji'] },
      { date: 'Sun 22', where: '✈', text: 'KIX→SFO', ref: [] },
    ],
    stays: ['palace-hotel-tokyo', 'kokuya', 'hyatt-centric-kanazawa', 'beniya-mukayu', 'sowaka'],
    altStays: [],
    dining: ['leffervescence', 'zeniya-kanazawa', 'kikunoi-honten', 'kodaiji-jugyuan'],
    doing: ['snow-monkeys', 'picchio-musasabi', 'hirata-sword', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['kenrokuen', 'higashi-chaya', 'zenkoji', 'arashiyama', 'sanzen-in-ohara', 'philosophers-path', 'kodaiji', 'gion'],
    costRows: [
      ['Flights', '$9,500'],
      ['Hotels — Palace 3n + Kokuya 2n (HB) + Kanazawa 1n + Mukayu 2n (HB) + Sowaka 5n', '$12,400'],
      ['Dining', '$3,800'],
      ['Experiences — sword $1,700, Heki kintsugi $600, kyudo $270, flying squirrels $170, owl café $60, both monkey parks $30', '$2,830'],
      ['Ground — Gran Class, expresses, transfers', '$1,200'],
    ],
    costTotal: '≈ $29,700',
    levers: `Kyoto days land Nov 17–22 — colour building but likely just before the forecast peak, in exchange for roughly $300/night cheaper rooms and the full Kanazawa crab-and-Kenrokuen alignment.`,
    verdict: `<strong>This one changed the most.</strong> Its old selling point was being the densest craft itinerary, and that is gone — Mutoh kintsugi, the Raku kiln, the indigo and the Kutani/yuzen day all came out. What is left is arguably a better trip: three wildlife encounters (Karuizawa flying squirrels, Jigokudani macaques, Iwatayama macaques), crab season, Kenrokuen at peak, and the country's best train seat, for $1,100 less. Watch the Nov 21–23 holiday weekend crowds at the tail end.`,
    verdictTone: 'good',
  },

  // ══════════════════════════════════════════════════════════════ 3 ══
  {
    num: 3,
    slug: 'wildlife-north',
    title: 'Wildlife North + Momiji Finale',
    tagline: 'Built around the one experience that got five thumbs up',
    dates: 'Sat Nov 14 → Sun Nov 29, 2026',
    length: '15 nights',
    route: ['Tokyo · 2n', 'E. Hokkaido · 4n', 'Kyoto · 6n'],
    routeNote: 'Open-jaw, returning from KIX',
    cost: '$29,300',
    costBand: '$28–30k',
    temp: 'Hokkaido 20–40°F',
    tempStatus: 'warn',
    bestFor: 'Ezo flying squirrel, cranes, and peak Kyoto',
    transport: {
      mode: 'Fly + self-drive + rail',
      text: `Eastern Hokkaido is effectively car-only, and it is where your road-trip instincts pay off: empty, beautiful roads. Rentals come with studless tyres fitted free. Drive in daylight only — sunset is about 4pm — and watch for dawn black ice. HND→Kushiro is 1h40 at $100–125 per person; returning is Kushiro→HND→ITM to reach Kyoto.`,
      ref: ['lexus-nx-japan', 'ana-the-room'],
    },
    hero: 'ezo-momonga',
    heroCard: ['tsurui-cranes', 'hinanoza', 'tofukuji'],
    pitch: `Ashly's most-wanted item on the entire wish list is the Ezo flying squirrel, marked with five thumbs up. This itinerary is the answer to that: four days in eastern Hokkaido with a guide, then six nights in Kyoto riding into the forecast foliage peak. It comes with a caveat the plan states plainly — late November delivers momonga, arriving cranes, swans, owls and foxes, but Hokkaido's postcard winter is a January-and-February trip.`,
    days: [
      { date: 'Sat 14', where: '✈', text: 'SFO→HND', ref: ['ana-the-room'] },
      { date: 'Sun 15', where: 'Tokyo', text: 'Land. <strong>Palace Hotel</strong>, one night. Recovery evening.', ref: ['palace-hotel-tokyo'] },
      { date: 'Mon 16', where: '→ Hokkaido', text: '<strong>Akiba Fukurou</strong>, the owl café, in the morning — Akihabara is on the way to Haneda — then HND→Kushiro in the afternoon. Pick up the 4WD. <strong>Akan Tsuruga Bessou Hinanoza</strong> on Lake Akan, 25 suites, every one with a private onsen.', ref: ['akiba-fukurou', 'hinanoza', 'lake-akan'] },
      { date: 'Tue 17', where: 'Akan / Tsurui', text: '<strong>Red-crowned cranes at the Tsurui-Ito sanctuary</strong> — feeding season starts mid-to-late November, so numbers are building, not yet the January–February 300-bird spectacle. Ural owl roost plus Ezo deer and fox with a local guide.', ref: ['tsurui-cranes'] },
      { date: 'Wed 18', where: 'Kussharo', text: '<strong>Whooper swans arriving at Lake Kussharo</strong> — the Kotan and Sunayu lakeside hot springs. Mt Io. Second night at Hinanoza.', ref: ['lake-kussharo', 'hinanoza'] },
      { date: 'Thu 19', where: 'Kushiro', text: 'Kushiro-Shitsugen wetland boardwalks. At dusk: <strong>the Ezo flying squirrel session</strong> — momonga emerge about 10 minutes after sunset at monitored burrows, and guides run these year-round with high success at known dens (≈ $200–300/couple). Overnight in Kushiro, or a third night at Hinanoza.', ref: ['kushiro-shitsugen', 'ezo-momonga', 'kushiro-stay'] },
      { date: 'Fri 20', where: '→ Kyoto', text: 'Morning momonga backup slot — weather insurance, since windy or rainy nights get cancelled. Fly Kushiro→HND→ITM. <strong>Sowaka</strong> in Kyoto.', ref: ['ezo-momonga', 'sowaka'] },
      { date: 'Sat 21 – Fri 27', where: 'Kyoto', text: 'The Itinerary 1 Kyoto week, compressed and now with room to breathe: <strong>Kikunoi</strong>, <strong>Jugyuan</strong>, <strong>Heki kintsugi</strong>, <strong>kyudo</strong>, the <strong>Iwatayama monkey park</strong> above Arashiyama, a day in <strong>Nara</strong> among the deer, and Eikando and Rurikoin — with the final days riding into forecast peak colour.', ref: ['kikunoi-honten', 'kodaiji-jugyuan', 'heki-kintsugi', 'kyudo', 'arashiyama-monkeys', 'nara-deer', 'eikando', 'rurikoin'], span: true },
      { date: 'Sat 28', where: 'Kyoto', text: 'Peak-colour free day. <strong>Cenci</strong> farewell.', ref: ['tofukuji', 'cenci-kyoto'] },
      { date: 'Sun 29', where: '✈', text: 'KIX→SFO', ref: [] },
    ],
    stays: ['palace-hotel-tokyo', 'hinanoza', 'kushiro-stay', 'sowaka'],
    altStays: [],
    dining: ['kikunoi-honten', 'kodaiji-jugyuan', 'cenci-kyoto'],
    doing: ['ezo-momonga', 'tsurui-cranes', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['lake-akan', 'lake-kussharo', 'kushiro-shitsugen', 'nara-deer', 'eikando', 'tofukuji', 'rurikoin', 'arashiyama', 'gion', 'kodaiji'],
    costRows: [
      ['Flights, international', '$9,500'],
      ['Domestic flights — HND–Kushiro, Kushiro–ITM via HND', '$900'],
      ['Hotels — Tokyo 1n + Hinanoza 3n (HB) + Kushiro 1n + Sowaka 6n', '$12,000'],
      ['Car — 4WD 4 days plus fuel and tolls', '$700'],
      ['Dining', '$3,600'],
      ['Experiences and guides — Hokkaido wildlife guiding $750, Heki kintsugi $600, kyudo $270, owl café $60, monkey park $10', '$1,690'],
      ['Ground', '$900'],
    ],
    costTotal: '≈ $29,300',
    levers: `Shiretoko is deliberately absent — the pass closes in early November, the Five Lakes trails close in late November, bear cruises are done, and the drift-ice eagles are a February show.`,
    verdict: `<strong>The cuts moved this one inside budget</strong> — dropping the matcha, the Raku kiln and the Tokyo kintsugi took it from $30,900 to about $29,300, and it is now the cheapest route that still delivers the flying squirrel Ashly actually wants.<br><br><strong>Honesty box.</strong> Late November delivers momonga, arriving cranes, swans, owls and foxes — genuinely good — but the iconic winter postcards (crane courtship in snow, the Otowa Bridge mist) need a January or February trip. Note too that Karuizawa now offers a flying squirrel on itineraries 1, 2 and 5 for about $170: a different, larger species with a >90% hit rate. If seeing <em>the Ezo momonga specifically</em> is the point, this is still the only route that does it. If seeing <em>a flying squirrel</em> is the point, Hokkaido is no longer required.`,
    verdictTone: 'warn',
  },

  // ══════════════════════════════════════════════════════════════ 4 ══
  {
    num: 4,
    slug: 'southern-warmth',
    title: 'Southern Warmth',
    tagline: 'The only one entirely inside your temperature band — and the best drive',
    dates: 'Sat Oct 31 → Sun Nov 15, 2026',
    length: '15 nights',
    route: ['Fukuoka · 2n', 'Kurokawa · 2n', 'Kagoshima · 1n', 'Yakushima · 3n', 'Kyoto · 6n'],
    routeNote: 'Open-jaw, returning from KIX',
    cost: '$28,200',
    costBand: '$27–29k',
    temp: '55–70°F throughout',
    tempStatus: 'best',
    bestFor: 'Warmth, road trip, most headroom in budget',
    transport: {
      mode: 'Fly + self-drive Kyushu',
      text: `The truest successor to your France, UK and Germany format: a Lexus through Aso caldera country is one of Japan's great drives, and rural onsen are awkward without a car. This is also the warmest itinerary — 55–70°F nearly throughout, and the only one fully inside the seeds temperature band.`,
      ref: ['lexus-nx-japan', 'ana-the-room'],
    },
    hero: 'aso-caldera',
    heroCard: ['gekkoju', 'shiratani-unsuikyo', 'sankara-yakushima'],
    pitch: `Start in Kyushu at 65°F, drive a Lexus across one of the largest volcanic calderas on earth, sleep in a villa with a private hot spring in the woods at Kurokawa, fly to a subtropical island of thousand-year-old cedars, and finish with six nights in Kyoto at pre-peak prices. It is the cheapest of the five, the warmest by a distance, and the closest in shape to the trips you have actually enjoyed before. The cost is that it skips Tokyo entirely — which means no sword smithing.`,
    days: [
      { date: 'Sat 31', where: '✈', text: 'SFO→HND, connecting HND→Fukuoka (or a through-ticket)', ref: ['ana-the-room'] },
      { date: 'Sun 1', where: 'Fukuoka', text: '<strong>The Ritz-Carlton Fukuoka</strong>. Yatai-district evening walk — for GF, stick to the counters rather than the stalls.', ref: ['ritz-carlton-fukuoka', 'fukuoka-yatai'] },
      { date: 'Mon 2', where: 'Fukuoka', text: '<strong>Goh</strong> dinner — Asia\'s 50 Best, 14 seats, single seating; French-Japanese means an easy gluten-free dialogue. <strong>The email window opens 60 days out — set a calendar alarm for 2 September</strong>, and target a Tuesday or Wednesday.', ref: ['goh-fukuoka'] },
      { date: 'Tue 3', where: '→ Kurokawa', text: 'Pick up the <strong>Lexus NX</strong> (Toyota Rent a Car premium, ≈ $250/day). Drive via Yufuin, 2.5 scenic hours. <strong>Gekkoju</strong> — 8 private villas, each with its own open-air onsen. Foliage here runs late Oct to mid Nov, so this is on time.', ref: ['lexus-nx-japan', 'yufuin', 'gekkoju'] },
      { date: 'Wed 4', where: 'Aso', text: 'The Aso caldera and the Kusasenri grasslands — the road-trip day. Kurokawa town stroll in yukata, with the rotenburo-hopping pass.', ref: ['aso-caldera', 'kurokawa-onsen-town'] },
      { date: 'Thu 5', where: '→ Kagoshima', text: 'Drive south, about 3 hours, via Kirishima shrine country. Drop the car. Shiroyama Hotel, or a night by the airport. Sakurajima views.', ref: ['kirishima', 'shiroyama-kagoshima', 'sakurajima'] },
      { date: 'Fri 6', where: 'Yakushima', text: '40-minute JAC turboprop. <strong>Sankara Hotel & Spa</strong> — Small Luxury Hotels, from the seeds list; suites include dinner at okas. It publishes its gluten-free accommodation outright.', ref: ['sankara-yakushima', 'okas-sankara'] },
      { date: 'Sat 7', where: 'Yakushima', text: '<strong>Shiratani Unsuikyo</strong> guided hike — the mossy "Princess Mononoke" forest. November is Yakushima\'s driest, clearest season.', ref: ['shiratani-unsuikyo'] },
      { date: 'Sun 8', where: 'Yakushima', text: 'Coastal loop drive: Oko Falls, Nagata beach, an onsen. okas French-Yakushima dinner.', ref: ['yakushima-coast', 'okas-sankara'] },
      { date: 'Mon 9', where: '→ Kyoto', text: 'Fly Yakushima→Kagoshima→ITM. <strong>Sowaka</strong> — early-to-mid November is <em>pre-peak pricing</em>, the quiet luxury window.', ref: ['sowaka'] },
      { date: 'Tue 10', where: 'Kyoto · Arashiyama', text: '<strong>Iwatayama monkey park</strong> at opening, then early Arashiyama — first colour around Nov 10–15 at the altitude edges. <strong>Kikunoi Honten</strong> in the evening.', ref: ['arashiyama-monkeys', 'arashiyama', 'kikunoi-honten'] },
      { date: 'Wed 11', where: 'Nara', text: '<strong>Nara</strong>: sika deer loose among the temples, Todai-ji\'s Great Buddha hall and the lantern avenue at Kasuga Taisha, 45 minutes each way. Gion in the evening.', ref: ['nara-deer', 'gion'] },
      { date: 'Thu 12', where: 'Kyoto', text: '<strong>Heki kintsugi</strong> in the morning — the one craft workshop kept. Eikando illumination opening nights.', ref: ['heki-kintsugi', 'eikando'] },
      { date: 'Fri 13', where: 'Kyoto · Ohara', text: 'Ohara and <strong>Sanzen-in</strong> — the moss garden and its jizo figures, well north of the city and quiet.', ref: ['sanzen-in-ohara'] },
      { date: 'Sat 14', where: 'Kyoto', text: '<strong>Kyudo</strong> session. <strong>Kodaiji Jugyuan</strong> farewell dinner plus the Kodai-ji illumination.', ref: ['kyudo', 'kodaiji-jugyuan', 'kodaiji'] },
      { date: 'Sun 15', where: '✈', text: 'KIX→SFO Polaris', ref: [] },
    ],
    stays: ['ritz-carlton-fukuoka', 'gekkoju', 'shiroyama-kagoshima', 'sankara-yakushima', 'sowaka'],
    altStays: [],
    dining: ['goh-fukuoka', 'okas-sankara', 'kikunoi-honten', 'kodaiji-jugyuan'],
    doing: ['shiratani-unsuikyo', 'arashiyama-monkeys', 'heki-kintsugi', 'kyudo'],
    places: ['aso-caldera', 'kurokawa-onsen-town', 'yufuin', 'sakurajima', 'kirishima', 'fukuoka-yatai', 'yakushima-coast', 'nara-deer', 'arashiyama', 'eikando', 'sanzen-in-ohara', 'gion', 'kodaiji'],
    costRows: [
      ['Flights, international (open-jaw HND in / KIX out)', '$9,500'],
      ['Domestic — HND–FUK, KOJ–Yakushima, Yakushima–KOJ–ITM', '$1,300'],
      ['Hotels — Ritz 2n + Gekkoju 2n (HB) + Kagoshima 1n + Sankara 3n + Sowaka 6n', '$10,600'],
      ['Car — Lexus 3 days, tolls and fuel, plus the Yakushima rental', '$1,100'],
      ['Dining', '$3,600'],
      ['Experiences — Heki kintsugi $600, Yakushima guide $300, kyudo $270, monkey park $10', '$1,180'],
      ['Ground', '$900'],
    ],
    costTotal: '≈ $28,200',
    levers: `In budget with headroom to about $27.5k via United or consolidator fares. Warmest, best road-trip content, and Sankara, Goh and Gekkoju are all seed-adjacent wins.`,
    verdict: `<strong>Still the cheapest and warmest — but the cuts helped it least, and the additions skip it entirely.</strong> It only loses $1,300 of activity spend because it never had the matcha or the Tokyo kintsugi, and because <strong>it skips Tokyo it is now the only route with no flying squirrel and no owl café</strong>. Its wildlife is the Iwatayama macaques, the Nara deer and whatever the Yakushima forest offers. Adding a 2-night Tokyo block (about $4,000) would buy back the sword smithing, the owl café and the Karuizawa flying squirrels in one move — that lever is worth more now than it was. The other trades are unchanged: Kyoto at building colour rather than peak, compensated by lower rates and thinner crowds. Seven Stars, also from the seeds, lives in Kyushu, but its waitlist runs about two years and October 2026 cabins are effectively gone.`,
    verdictTone: 'good',
  },

  // ══════════════════════════════════════════════════════════════ 5 ══
  {
    num: 5,
    slug: 'grand-tour',
    title: 'The Grand Tour',
    tagline: 'The stretch. Everything, at the cost of both budget rules',
    dates: 'Sat Nov 14 → Thu Dec 3, 2026',
    length: '19 days / 17 nights',
    route: ['Tokyo · 3n', 'E. Hokkaido · 3n', 'Kyoto · 6n', 'Hakone · 2n', 'Tokyo · 1n'],
    routeNote: 'Out of HND, landing Thursday',
    cost: '$35,500',
    costBand: '$34–37k',
    temp: 'Mixed',
    tempStatus: 'warn',
    bestFor: 'Everything — breaks budget and the Sat/Sun return',
    transport: {
      mode: 'Fly + Hokkaido self-drive + rail',
      text: `The everything trip: momonga and cranes <em>and</em> the densest peak-Kyoto colour (Nov 29 – Dec 3 forecast maximum) <em>and</em> Gora Kadan. It exists to show what the window physically allows.`,
      ref: ['ana-the-room', 'lexus-nx-japan', 'shinkansen-green-car'],
    },
    hero: 'rurikoin',
    heroCard: ['ezo-momonga', 'gora-kadan', 'eikando'],
    pitch: `It is the only single-trip answer to "peak Kyoto plus flying squirrels plus Gora Kadan." Nineteen days: the Tokyo crafts block, the Hokkaido wildlife loop, six Kyoto nights riding into the forecast foliage crest of Nov 29 – Dec 3, and two closing kaiseki nights at Gora Kadan. It breaks two of your own rules — the budget ceiling and the Saturday/Sunday return — and it is included so the trade-off is visible rather than theoretical.`,
    flow: `Tokyo — Hirata sword, the owl café, a Karuizawa day for the musasabi, L'Effervescence → fly to Kushiro for Hinanoza, the Tsurui cranes and the momonga session, exactly as in Itinerary 3 → fly to Kyoto for six nights riding into the forecast crest, with Kikunoi, Jugyuan, the Heki kintsugi, kyudo, the Iwatayama macaques, Nara and the illuminations → Gora Kadan for two kaiseki nights → HND→SFO on Thursday 3 December. Both flying squirrel species, in one trip.`,
    days: [
      { date: 'Sat 14 – Tue 17', where: 'Tokyo · Karuizawa', text: 'Land and settle at the <strong>Palace Hotel</strong>. <strong>Hirata sword smithing</strong> in Ome, <strong>Akiba Fukurou</strong> the owl café, a day out to Karuizawa for the <strong>flying squirrels</strong>, and <strong>L\'Effervescence</strong>. This is the only route with enough Tokyo time left over for teamLab or a Yanaka afternoon.', ref: ['palace-hotel-tokyo', 'hirata-sword', 'akiba-fukurou', 'picchio-musasabi', 'leffervescence', 'teamlab'], span: true },
      { date: 'Wed 18 – Sat 21', where: 'E. Hokkaido', text: 'Fly to Kushiro, pick up the 4WD. <strong>Hinanoza</strong> on Lake Akan, the <strong>Tsurui cranes</strong>, the swans at Kussharo, and the <strong>Ezo flying squirrel</strong> session at dusk — as in Itinerary 3, with a backup night for weather.', ref: ['hinanoza', 'tsurui-cranes', 'lake-kussharo', 'ezo-momonga'], span: true },
      { date: 'Sun 22 – Fri 27', where: 'Kyoto', text: 'Six nights at <strong>Sowaka</strong> riding into the forecast crest: <strong>Kikunoi</strong>, <strong>Jugyuan</strong>, <strong>Heki kintsugi</strong>, <strong>kyudo</strong>, the <strong>Iwatayama monkey park</strong>, a day in <strong>Nara</strong>, Ohara, and the Eikando and Kodai-ji illuminations at their peak.', ref: ['sowaka', 'kikunoi-honten', 'kodaiji-jugyuan', 'heki-kintsugi', 'kyudo', 'arashiyama-monkeys', 'nara-deer', 'eikando', 'rurikoin', 'tofukuji'], span: true },
      { date: 'Sat 28 – Mon 30', where: 'Kyoto → Hakone', text: 'The last Kyoto days at the densest forecast colour, then the shinkansen to <strong>Gora Kadan</strong> for two kaiseki nights and the cypress onsen.', ref: ['gora-kadan', 'lake-ashi'], span: true },
      { date: 'Tue 1 – Thu 3', where: 'Hakone → Tokyo → ✈', text: 'Back to Tokyo for a final night, then HND→SFO, landing Thursday 3 December.', ref: ['palace-hotel-tokyo'], span: true },
    ],
    stays: ['palace-hotel-tokyo', 'hinanoza', 'sowaka', 'gora-kadan'],
    altStays: [],
    dining: ['leffervescence', 'kikunoi-honten', 'kodaiji-jugyuan'],
    doing: ['ezo-momonga', 'tsurui-cranes', 'picchio-musasabi', 'hirata-sword', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
    places: ['rurikoin', 'eikando', 'tofukuji', 'kodaiji', 'nara-deer', 'lake-akan', 'lake-kussharo', 'lake-ashi', 'gion', 'arashiyama'],
    costRows: [
      ['Flights, international plus domestic', '$10,800'],
      ['Hotels — 17 nights: Palace 3 + Hinanoza 3 + Sowaka 6 + Gora Kadan 2 + Tokyo 1', '$19,500'],
      ['Dining, experiences, car and ground', '$5,200'],
    ],
    costTotal: '≈ $35,500',
    levers: `The cuts took $4,000 off. Cutting Hakone as well (−$3,500) lands it near $32,000 — but Gora Kadan is half the reason this itinerary exists.`,
    verdict: `<strong>Still breaks two seed rules</strong> — the budget and the Saturday/Sunday return, since it lands on Thursday 3 December. It is included because it is the only single-trip answer to "peak Kyoto plus flying squirrels plus Gora Kadan." Worth noting that the Karuizawa tour weakens that argument: itineraries 1 and 2 can now show you a flying squirrel without the Hokkaido leg, which is most of what made this trip nineteen days long.`,
    verdictTone: 'warn',
  },
];

// Every wish from seeds.md, checked against each itinerary.
// `has` is an entity slug looked up in the itinerary's own lists; `manual` overrides per itinerary number.
export const wishlist = [
  { label: 'Kikunoi Honten', note: 'named in seeds', has: 'kikunoi-honten' },
  { label: 'Kodaiji Jugyuan', note: 'named in seeds', has: 'kodaiji-jugyuan' },
  { label: 'Gora Kadan', note: 'named in seeds', has: 'gora-kadan' },
  { label: 'A Relais & Châteaux stay', note: 'seeds: “anything in R&C Japan”', manual: { 1: 'yes', 2: 'yes', 3: 'no', 4: 'no', 5: 'yes' }, why: { 3: 'Hinanoza is the ceiling out east', 4: 'Sankara is SLH, not R&C' } },
  { label: 'A Michelin 3-Key hotel', note: 'seeds: favourite is Auberge du Soleil', manual: { 1: 'yes', 2: 'yes', 3: 'yes', 4: 'no', 5: 'yes' }, why: { 4: 'skips Tokyo; Sankara holds 1 Key' } },
  { label: 'Hirata sword smithing', note: 'Ashly 👍', has: 'hirata-sword' },
  { label: 'Kintsugi', note: 'Ashly 👍👍 — the deep Kyoto one only', has: 'heki-kintsugi' },
  { label: 'Kyudo', note: 'named in seeds 👍', has: 'kyudo' },
  { label: 'An owl café', note: 'Ashly asked for this', has: 'akiba-fukurou' },
  { label: 'A flying squirrel', note: 'Ashly 👍×5 — the top wish', has: ['ezo-momonga', 'picchio-musasabi'], why: { 1: 'musasabi, Karuizawa', 2: 'musasabi, Karuizawa', 3: 'the Ezo momonga itself', 4: 'no Tokyo, so no Karuizawa', 5: 'both species' } },
  { label: 'Wildlife photography', note: 'a stated interest', manual: { 1: 'yes', 2: 'yes', 3: 'yes', 4: 'part', 5: 'yes' }, why: { 1: 'squirrels, Nara deer, macaques', 2: 'squirrels + two macaque troops', 3: 'momonga, cranes, swans', 4: 'macaques and Nara deer only', 5: 'everything' } },
  { label: 'Snow monkeys', note: 'Ashly 👍', has: 'snow-monkeys' },
  { label: 'Crane photography', note: 'named in seeds', has: 'tsurui-cranes' },
  { label: 'Sankara Yakushima', note: 'named in seeds', has: 'sankara-yakushima' },
  { label: 'Raku pottery, Shoraku kiln', note: 'in seeds — you cut it', manual: { 1: 'no', 2: 'no', 3: 'no', 4: 'no', 5: 'no' }, why: { 1: 'cut: three ceramics workshops was too many' } },
  { label: 'Indigo dyeing', note: 'in seeds — you cut it', manual: { 1: 'no', 2: 'no', 3: 'no', 4: 'no', 5: 'no' }, why: { 1: 'cut, though Ohara stays' } },
  { label: 'Uji matcha experience', note: 'in seeds — you cut it', manual: { 1: 'no', 2: 'no', 3: 'no', 4: 'no', 5: 'no' }, why: { 1: 'cut: not worth $2,600' } },
  { label: '55–75°F throughout', note: 'a stated requirement', manual: { 1: 'part', 2: 'part', 3: 'no', 4: 'yes', 5: 'no' }, why: { 1: '45–65°F — a little under', 2: 'Nagano in the 40s', 3: 'Hokkaido 20–40°F', 5: 'mixed, plus December' } },
  { label: 'Inside the $30k budget', note: 'stated $15–30k', manual: { 1: 'no', 2: 'part', 3: 'part', 4: 'yes', 5: 'no' }, why: { 1: '$36.2k; $31k with levers', 2: '$30.8k — just over', 3: '$30.9k — just over', 5: '$39.5k' } },
  { label: 'Leave and return Sat/Sun', note: 'stated preference', manual: { 1: 'yes', 2: 'yes', 3: 'yes', 4: 'yes', 5: 'no' }, why: { 5: 'lands Thursday 3 December' } },
  { label: 'Peak autumn colour in Kyoto', note: 'the reason for these dates', manual: { 1: 'yes', 2: 'part', 3: 'yes', 4: 'no', 5: 'yes' }, why: { 2: 'colour building, just before peak', 4: 'first colour only, early Nov' } },
];

export const recommendation = [
  ['Gora Kadan and peak Kyoto colour are the point', 'The seeds trip, and the cuts brought it from $36.2k to $34.1k without touching a hotel', 1],
  ['You want the most wildlife for the money', 'Flying squirrels and two macaque troops on one rail line, plus crab week and Kenrokuen at peak, at $29.7k', 2],
  ['It has to be the Ezo momonga specifically', 'Now $29.3k and inside budget. But Karuizawa puts a flying squirrel on itineraries 1, 2 and 5 for $170, so ask whether it is the species or the animal you want', 3],
  ['Warmth, a road trip and the lowest number', 'Cheapest at $28.2k and the only all-temp-band option — but the only route with no flying squirrel and no owl café', 4],
  ['Once-in-a-decade mood', 'Everything, still over budget at $35.5k, and Karuizawa has weakened its main argument', 5],
];
