// THE PLAN. Itinerary 1B, chosen on 15 August 2026. This is the live document — the one file a
// PR that changes the trip should need to open.
//
// It carries its own flights, transport, gluten-free and booking copy rather than importing the
// shared foundations from content/shared.mjs. That is deliberate: on a page about one trip nothing
// is "shared", it is just part of the trip, and the material reads better named to the actual
// flights, the actual kitchens and the actual dates. shared.mjs still exists for the archive, which
// really does compare seven itineraries. If a fact changes in both, change it in both.
//
// Every change here should also get an entry in content/history.mjs.

export const plan = {
  // `num` and `variantOf` are kept because the archive's comparison tables still key off them.
  // 1D is the fourth fork of Itinerary 1 — it keeps 1B's flights, its Tokyo week and its Kyoto
  // dates, and replaces the two stops in between.
  num: '1D',
  slug: 'plan',
  variantOf: 1,
  decided: '23 August 2026',
  title: 'The Classic, with Nikko and Izu',
  tagline: 'Fifteen nights — Tokyo, four at 1,270m on Lake Chuzenji, two in a ryokan founded in 1484 on the Izu peninsula, and the same Kyoto week pointed north at the early colour',
  dates: 'Fri Nov 6 → Sun Nov 22, 2026',
  length: '15 nights',
  route: ['Tokyo · 4n', 'Okunikko · 4n', 'Shuzenji · 2n', 'Kyoto · 5n'],
  routeNote: 'Open-jaw — in to Tokyo (HND), home from Osaka (KIX), landing 22 November with three clear days before Colorado',
  cost: '$66,700',
  costBand: '$66–68k',
  temp: '32–60°F — Okunikko is the cold part',
  tempStatus: 'warn',
  bestFor: 'The version that is actually booked',

  // ── Getting there ────────────────────────────────────────────────
  flights: {
    title: 'Getting there',
    sub: '≈ $9,500 per couple, business, open-jaw — in to Tokyo, home from Osaka. Unchanged by the replan.',
    points: [
      `<strong>Out: Friday 6 November, SFO→HND on ANA “The Room.”</strong> A 28-inch-wide lie-flat with a closing door, and the best business product on the route. SFO frequencies alternate between the new and the old configuration, so <strong>verify the seat map before ticketing</strong> — the seat is the whole reason to choose this flight. About $4,500–5,500 per person booked 3–6 months out. <em>Friday rather than Saturday is not a detail: that departure is what pays for the fifteenth night.</em>`,
      `<strong>Home: Sunday 22 November, KIX→SFO on United Polaris.</strong> This trip ends in Kyoto, and United is the only SFO–KIX nonstop. Book it as a single United multi-city ticket — SFO→HND out, KIX→SFO back — which prices within about $0–500 of a normal round trip and saves a half-day backtrack to Tokyo on the last morning. The flight lands at SFO the same day it leaves Japan, so Sunday out of Osaka is Sunday home.`,
      `<strong>Kyoto→KIX on the last morning</strong> is the Haruka limited express, about 75–80 minutes from Kyoto Station. <em>Reserve the seats.</em> 22 November is the middle day of a three-day national holiday and the station will be heavy.`,
      `<strong>The $2,000 lever, if you want it.</strong> JAL out of SFO still flies its older Sky Suite — the new A350 suite is not on this route — and consolidator fares run $3,400–4,800 round trip. Cheaper, and a materially worse seat for eleven hours. <em>It is a more interesting lever than it was: this trip costs $30,000 more than the one it replaced.</em>`,
    ],
    ref: ['ana-the-room'],
  },

  // ── Getting around ───────────────────────────────────────────────
  transport: {
    mode: 'Rail, plus two days of car on Izu',
    text: `The old plan was rail the whole way and said so proudly. This one cannot be: <strong>Okunikko and the Izu peninsula are both places where the sights are strung along roads rather than lines</strong>. So it is rail for every transfer between bases, and a rental car picked up at Mishima on the way into Izu and dropped at Mishima on the way out — which works only because Mishima is on the route anyway.`,
    points: [
      `<strong>Sunday 15 November is the hard day, and it is about six hours.</strong> Lake Chuzenji to the Izu peninsula crosses the whole Kanto plain. The routing that works is the bus down the Irohazaka to <em>JR</em> Nikko, Utsunomiya, the Tohoku shinkansen into Tokyo, and the Tokaido on to Mishima. <strong>Not Tobu</strong> — Tobu is quicker on paper but puts you down at Asakusa, and you then cross Tokyo with two cases.`,
      `<strong>The hired car is not the answer, which is the surprise.</strong> Chugushi to Shuzenji by road is 330–360 km around Tokyo on the Ken-Ō-dō — five to six hours moving, six to seven realistically, at <strong>¥150,000–250,000</strong>. It is no faster than the train and costs seven times as much. It buys door-to-door luggage handling and nothing else.`,
      `<strong>So forward the bags instead — Nikko straight to Kyoto, past Izu entirely.</strong> Send them on the 13th rather than the 15th: Okunikko is a mountain address and next-day delivery to Kansai is not guaranteed from it the way it is from a city hotel. Two nights on Izu are done on overnight bags. $15–22 a bag.`,
      `<strong>The rental car is two days on Izu, from Mishima.</strong> Toyota Rent a Car is two minutes from the shinkansen exit, open 08:00–20:00. You pass through Mishima on the 15th, so the pickup costs nothing in time. <strong>Japan accepts only the 1949 Geneva IDP</strong> — AAA issues it, $20, and it is a physical booklet with no digital version, so an in-branch visit is the only fast route. <em>This has a lead time and it starts now.</em>`,
      `<strong>Green Car on the trunk route, booked on smartEX.</strong> Mishima→Kyoto is a direct Hikari in 1h51 — six a day, on a clean two-hourly clockface at :46. Reserve rather than turn up: late November is peak season on every train in this plan.`,
      `<strong>In Kyoto, buy the ¥1,100 Subway &amp; Bus 1-Day Pass for the Takao day.</strong> It covers the whole thing. The bus-only pass was discontinued in 2024 — the combined one is what survives.`,
    ],
    ref: ['shinkansen-green-car'],
  },
  hero: 'asaba-ryokan',
  heroCard: ['ritz-carlton-nikko', 'asaba-ryokan', 'hotel-the-mitsui-kyoto'],
  pitch: `<strong>This is the first version of the trip in which every bed is booked rather than estimated.</strong> Aman Tokyo, the Ritz-Carlton on Lake Chuzenji, Asaba in Shuzenji and Hotel The Mitsui in Kyoto — four confirmations, fifteen nights, the same flights and the same shape as before. What changed is the middle: Gora Kadan came back full for 11–13 November, and rebuilding around what could actually be held moved the trip from Hakone and the Northern Alps to <strong>Okunikko and the Izu peninsula</strong>.<br><br><strong>Two of Japan's seven three-Michelin-Key properties are on it.</strong> Asaba, founded in 1484 and run by the same family for ten generations, with a working Noh stage across its pond; and Hotel The Mitsui, on three hundred years of family land facing Nijo Castle, with a hot spring drawn from a thousand metres beneath the building. They are also the two best-evidenced kitchens on the trip for a coeliac guest.<br><br><strong>The Tokyo week survived intact</strong> — the flying squirrels at Karuizawa, the Hirata forge at Ome, L'Effervescence on the only night it opens. <strong>And the Kyoto week still points north</strong>, at Takao, Ohara, Rurikoin, Kurama and Kibune, which colour one to two weeks before the city floor. From the new base that week is <em>better</em> served, not worse: Takao is forty minutes closer and Nijo Castle is across the street.<br><br><strong>What it costs is the headline.</strong> $66,700 against $36,200 — the lodging line alone nearly tripled, and six half-board dinners became two.`,
  days: [
    { date: 'Fri 6', where: '✈', text: 'SFO→HND, ANA The Room. <em>The Friday departure is the one that pays for the fifteenth night.</em>', ref: ['ana-the-room'] },
    { date: 'Sat 7', where: 'Tokyo', text: 'Land at 04:50, private transfer, gentle evening. <strong>Aman Tokyo</strong> — booked, four nights, confirmation 62649SG260399. <em>The room is not ready until 15:00; the spa and the Imperial Palace East Gardens are the answer.</em>', ref: ['aman-tokyo'] },
    { date: 'Sun 8', where: 'Tokyo', text: 'A deliberately light first day. Meiji Jingu. <em>The Jingu Gaien ginkgo are still turning this early — they gold up around 20 Nov.</em> Afternoon at <strong>Akiba Fukurou</strong>, the owl café. <em>No dinner booking tonight: L\'Effervescence is closed Sundays.</em>', ref: ['meiji-jingu', 'omotesando-ginkgo', 'akiba-fukurou'] },
    { date: 'Mon 9', where: 'Karuizawa', text: '<strong>Flying squirrels.</strong> Shinkansen out after lunch, Picchio\'s <strong>musasabi watching tour</strong> at dusk, back in Tokyo by evening. <em>The season ends 30 November, so these are among the last slots of the year.</em>', ref: ['picchio-musasabi'] },
    { date: 'Tue 10', where: 'Tokyo · Ome', text: '<strong>Hirata sword smithing</strong> — forge a small katana with the husband-and-wife smiths, engraved and shipped home. Back in town for <strong>L\'Effervescence</strong>, 3★, with its printed GF menu. <em>Tuesday is the only night of this Tokyo block it can happen.</em>', ref: ['hirata-sword', 'leffervescence'] },
    { date: 'Wed 11', where: '→ Okunikko', text: 'Up to <strong>Lake Chuzenji at 1,270m</strong> and the <strong>Ritz-Carlton Nikko</strong> — booked, four nights, confirmation 89324734, a Lake View suite with a balcony. <em>The hotel has its own natural hot spring, which matters more here than it would anywhere else on this trip.</em>', ref: ['ritz-carlton-nikko', 'lake-chuzenji'] },
    { date: 'Thu 12', where: 'Nikko', text: '<strong>Down the mountain, because that is where the colour is.</strong> <strong>Toshogu</strong> and its Yomeimon gate, Rinnoji, Taiyuin and the cryptomeria avenue; the <strong>Shinkyo</strong> bridge; and <strong>Kanmangafuchi</strong>, a gorge lined with seventy Jizo figures in red bibs. <em>Lower Nikko sits at about 600m and peaks early-to-mid November — you are on it.</em>', ref: ['nikko-toshogu', 'kanmangafuchi'] },
    { date: 'Fri 13', where: 'Okunikko', text: '<strong>The lake day.</strong> <strong>Kegon Falls</strong> from the observation deck, the boat across Lake Chuzenji, the Italian and British Embassy villas on the south shore, and Ryuzu Falls up the Senjogahara road. <em>Send the bags to Kyoto today, not on the 15th — this is a mountain address and next-day to Kansai is not a promise.</em>', ref: ['lake-chuzenji'] },
    { date: 'Sat 14', where: 'Okunikko', text: '<strong>The day that stays put</strong>, and the one the four-night booking is really for. The hot spring, the lake, and whatever the week has rained off. <em>Do not schedule this one. Sunday is six hours long.</em>', ref: ['ritz-carlton-nikko'] },
    { date: 'Sun 15', where: '→ Shuzenji', text: '<strong>The hard day.</strong> Leave at 08:20 — bus down the Irohazaka, JR to Utsunomiya, shinkansen to Tokyo, Tokaido to Mishima, <strong>collect the rental car</strong>, and drive in. About six hours, and you are at <strong>Asaba</strong> by around 14:30 against an 18:00 check-in deadline. Villa Tenko, and dinner in the room. <em>The Irohazaka jam is an October problem — by now the lake-level colour is finished and the traffic with it.</em>', ref: ['asaba-ryokan'] },
    { date: 'Mon 16', where: 'Izu', text: '<strong>The car day.</strong> Either the wasabi — Joren Falls, a working tatami-ishi farm, and the <strong>Ikadaba terraces</strong>, fifteen hectares of them and a UNESCO-recognised agricultural heritage — or Fuji, from Darumayama at sunrise and the cape at Toi at dusk. Evening: the <strong>bamboo path</strong> lit to 23:00, with a cut-paper projection from 20:00, three minutes from the door. <em>Room change to Moegi, looking at the Noh stage.</em>', ref: ['asaba-ryokan', 'shuzenji-onsen'] },
    { date: 'Tue 17', where: '→ Kyoto', text: 'Drop the car at Mishima and take the <strong>09:46 Hikari</strong> — direct, 1h51, Kyoto at 11:37. <strong>Hotel The Mitsui Kyoto</strong>, booked, five nights, confirmation R9GZA4213593. <em>Kikunoi is closed today — the 3rd Tuesday — which is exactly why it is on Thursday.</em> Nijo Castle is across the street if the evening event is running.', ref: ['hotel-the-mitsui-kyoto'] },
    { date: 'Wed 18', where: 'Kyoto · Takao', text: '<strong>Takao</strong>, and it is forty minutes closer than it was from Gion — two subway stops west to Uzumasa Tenjingawa, then City Bus 8, skipping the Kyoto Station scrum entirely. Jingo-ji up its stone staircase, the clay-disc throw off the terrace, and Kozan-ji below. <em>Kyoto\'s own tourism pages call Takao the earliest colour in the city.</em>', ref: ['takao'] },
    { date: 'Thu 19', where: 'Kyoto · north', text: '<strong>Ohara</strong> and Sanzen-in\'s moss garden — and the hotel\'s 1703 gate was built for the court attached to this temple, so you sleep behind it and then go and see where it came from. <strong>Rurikoin</strong> at Yase if you hold a reservation. <strong>Kikunoi Honten</strong> in the evening.', ref: ['sanzen-in-ohara', 'rurikoin', 'kikunoi-honten'] },
    { date: 'Fri 20', where: 'Kyoto · Arashiyama', text: '<strong>Iwatayama monkey park</strong> at opening, then the bamboo grove and Tenryu-ji — fifteen minutes better from here than from Gion. Back east for <strong>Heki kintsugi</strong> in the afternoon and <strong>Eikandō</strong>\'s illumination after it, which is a nine-minute ride to Keage with no change.', ref: ['arashiyama-monkeys', 'arashiyama', 'heki-kintsugi', 'eikando'] },
    { date: 'Sat 21', where: 'Kyoto', text: '<strong>Kyudo</strong> in the morning, then <strong>Kurama and Kibune</strong> on the Eizan line, and the <strong>Kodaiji Jugyuan</strong> farewell dinner with the illumination next door. <em>This is the highest-risk day of the trip: day one of a three-day national holiday, on a two-car railway that leaves people on platforms in ordinary autumn weather. Go at opening or not at all, and book the hotel car for the evening.</em>', ref: ['kurama-kibune', 'kyudo', 'kodaiji-jugyuan', 'kodaiji'] },
    { date: 'Sun 22', where: '✈', text: 'A free morning, then <strong>lunch at FORNI</strong> downstairs — 11:30, garden views, no travel between the last meal and the car. Out at 13:30 for the Haruka and KIX→SFO Polaris at 18:35, landing Sunday. Three clear days before Colorado.', ref: ['hotel-the-mitsui-kyoto'] },
  ],
  stays: ['aman-tokyo', 'ritz-carlton-nikko', 'asaba-ryokan', 'hotel-the-mitsui-kyoto'],
  dining: ['leffervescence', 'kikunoi-honten', 'kodaiji-jugyuan'],
  doing: ['hirata-sword', 'picchio-musasabi', 'akiba-fukurou', 'heki-kintsugi', 'arashiyama-monkeys', 'kyudo'],
  places: ['nikko-toshogu', 'lake-chuzenji', 'kanmangafuchi', 'shuzenji-onsen', 'takao', 'kurama-kibune', 'sanzen-in-ohara', 'rurikoin', 'eikando', 'kodaiji', 'arashiyama', 'gion', 'meiji-jingu', 'omotesando-ginkgo'],
  costRows: [
    ['Flights (open-jaw business) — unchanged', '$9,500'],
    ['Hotels — Aman 4n $14,640 · Ritz-Carlton Nikko 4n $11,225 · Asaba 2n half board $7,970 · Mitsui 5n $10,790', '$44,625'],
    ['Dining — only two of the fifteen dinners are now included in a room rate, against six before', '$7,900'],
    ['Experiences — sword $1,700, kintsugi $600, kyudo $270, Shuzenji washi $200, Mitsui private onsen $165, flying squirrels $170, owl café $60, wasabi $22, monkey park $10, entries', '$3,230'],
    ['Ground — Green Car, the six-hour transfer, two days of car on Izu, transfers, takkyubin', '$1,300'],
    ['Temple entries, illuminations and the Kyoto day pass', '$150'],
  ],
  costTotal: '≈ $66,700',

  costModel: `Per-couple. <strong>Four of the six lines are now facts rather than estimates</strong> — the hotels are booked and the numbers above are the confirmed totals, not forecasts. FX at ¥150/$.<br><br><strong>The change worth understanding is the dining line, which roughly doubled.</strong> The old plan had six of fifteen dinners inside a room rate — Gora Kadan three times, Myojinkan three times — each a set menu a kitchen had agreed to make gluten-free weeks in advance. This one has two, both at Asaba. The Ritz-Carlton is booked on a Member Flexible Rate whose charge breakdown is room, service and tax with no food line at all, so four dinners and four breakfasts at 1,270m are unbought. <strong>A 5–8% buffer is not included.</strong>`,

  verdict: `<strong>What you give up, and it is a real loss.</strong> Hakone entirely — the Open-Air Museum, the Pola, Owakudani, the torii standing in Lake Ashi, and the teppanyaki night at Itoh Dining that was the easiest coeliac dinner of the trip. Matsumoto entirely — the 1594 keep and the Kusama collection. And the gorge at 1,050m with the stay-put Monday in it. Six nights of the old plan are gone and nothing here replaces them exactly.<br><br><strong>The honest problem with Okunikko.</strong> The Ritz sits on Lake Chuzenji at 1,270m, and <em>lake-level colour there peaks in early-to-mid October</em>. By 11 November the trees around the hotel are bare and it is near freezing at night. The good foliage on those dates is six hundred metres downhill at Toshogu, which is a forty-minute bus ride away. This is not a disaster — it means the hotel is a warm room with a hot spring in a stark winter landscape, and the sightseeing happens down the hill — but it is not what four nights at a lake usually means, and it is the single thing most worth re-examining before <strong>14 October</strong>, when ¥1,330,000 stops being refundable.<br><br><strong>Izu has the same problem, more mildly.</strong> Shuzenji peaks late November into early December; 2024 did not crest until the first week of December. On 15–17 November expect ten to thirty per cent. What you get instead is thin crowds and a ryokan that is the point of the stop regardless.<br><br><strong>What you actually get.</strong> Two of Japan's seven three-Key properties, back to back with Aman. An inn founded in 1484 with a Noh stage over its pond, and the best-documented coeliac kitchen on the trip. A hot spring in the basement of your Kyoto hotel after three cold mountain days. And a Kyoto week that the base change made <em>better</em> — Takao forty minutes closer, Arashiyama fifteen, Nijo Castle across the street, and two Michelin restaurants inside a ten-minute walk.<br><br><strong>And the thing that has not changed at all.</strong> Takao, Kurama, Kibune, Ohara and Rurikoin are all at their best precisely when you are there, and all of them are skipped by most visitors, who are off chasing the central temples. That was the argument for these dates in August and it survives the replan untouched.`,
  verdictTone: 'warn',

  // ── Gluten-free ──────────────────────────────────────────────────
  glutenFree: {
    title: 'Gluten-free, kitchen by kitchen',
    sub: 'For Ashly. The replan made this harder, not easier: six set dinners inside a hotel stay became two, and four nights at 1,270m are now bought à la carte in a place with almost no alternative dining.',
    points: [
      `<strong>Say 小麦アレルギー — wheat allergy — not "gluten-free."</strong> Japanese kitchens treat アレルギー as a medical instruction; グルテンフリー alone reads as a wellness preference and is taken far less seriously. セリアック病 is accurate but poorly recognised by restaurant staff. And note that <strong>Japan has no mandatory allergen labelling for restaurant food</strong>, only for packaged goods — which is why the advance letter does more work than reading a menu on the night.`,
      `<strong>Asaba is the best-evidenced kitchen on the trip</strong>, and the one with the tightest deadline. It is specifically cited in the ryokan literature as having a celiac-specific <em>written confirmation</em> track record; dinner is served in-room, so there is no shared buffet and one server owns every course; and omakase means the meal is built from scratch rather than adapted. <strong>But full prepayment is required at reservation</strong> — so the gluten-free answer has to arrive before the money does, not four to six weeks out like everything else.`,
      `<strong>The Ritz-Carlton Nikko is the exposure.</strong> Four nights, room-only, at altitude, in an area with very little else within reach on a November evening. Ask Marriott whether a dining-inclusive rate exists for those nights — at this price point it usually does — and send the brief naming <em>every restaurant on the property separately</em>, because each kitchen is its own answer.`,
      `<strong>Hotel The Mitsui has a real process and an honest disclaimer.</strong> Allergies are taken at booking and re-checked at the table, and there is a hypoallergenic menu covering all eight mandatory allergens including wheat. But one kitchen and one dishwashing line serve every outlet, the hotel says plainly it cannot guarantee an allergen-free plate, and it reserves the right to refuse a booking for a severe allergy. <strong>No first-hand coeliac report about TOKI or FORNI exists anywhere</strong> — a gap, not a reassurance. FORNI is the more tractable: an Italian kitchen gives you grilled fish, roast meat, risotto and vegetables without going near the pizza oven.`,
      `<strong>Kikunoi has no gluten-free field on a reservation form, because it has no form.</strong> Booking is phone or email only — +81 75-561-0015, honten@kikunoi.co.jp. Let the Mitsui concierge do it; a three-Key hotel will have the relationship. There is likewise no first-hand coeliac report about Kikunoi, so ask for a written reply rather than assuming.`,
      `<strong>The mechanics, for a kaiseki kitchen.</strong> Dashi itself is fine — katsuobushi and kombu carry no wheat. The risks are <strong>shoyu</strong>, which is roughly half wheat by grist and is the single biggest hidden vector; <strong>barley miso</strong> (rice miso is generally safe); the <strong>fried course</strong>, which almost every kaiseki sequence has, and its shared oil; and <strong>soba</strong>, which is a wheat blend unless it is juwari, and even then is boiled in shared water. Ask for <strong>たまり醤油（小麦不使用）</strong> by name and carry certified packets.`,
      `<strong>Shuzenji is a soba town, which for a coeliac means the local food is largely off-limits.</strong> There is exactly one dedicated gluten-free restaurant — Vieni KANDA, whose chef has a wheat allergy himself and mills pasta from pea and brown-rice flour — and <strong>it is closed Mondays and Tuesdays</strong>, which is both of your full days. Sunday lunch on arrival is the only window, and the restaurant itself warns that the building previously housed a ramen shop and a bakery. Plan to eat both dinners at Asaba.`,
      `<strong>Corrections to the old brief.</strong> "Little Bird" is in Tokyo, not Kyoto — there is no Kyoto branch and there never was. The Kyoto fallbacks that do exist are <strong>Kushikura Honten</strong>, charcoal yakitori thirteen minutes' walk from the hotel where everything can be ordered shio-yaki rather than tare, and <strong>Toshoan</strong>, a dedicated gluten-free kitchen nine minutes from Nijo Castle. <strong>Sézanne still explicitly refuses gluten-free requests.</strong>`,
      `<strong>Send the brief in early October</strong> — except Asaba, which goes now. A detailed reply naming the dishes it would change is the signal a kitchen has understood; "no problem, we will accommodate" usually means it heard "no bread."`,
    ],
  },

  // ── Booking calendar ─────────────────────────────────────────────
  bookNow: {
    title: 'Book this now',
    sub: 'Standing at 23 August 2026. The four hotels are done — this is everything the replan left open, ordered by when the window shuts.',
    groups: [
      ['Today', '<strong>Reply to Asaba.</strong> Confirm 15 November in Villa Tenko <em>and</em> 16 November in Moegi as a single two-night stay with a room change; ask what is under renovation and whether the rate moves given the indoor baths are shut and the quote is 22% above last year; and put the coeliac brief in the same message, because full prepayment is required at reservation. <strong>And start the International Driving Permit</strong> — Japan accepts only the 1949 Geneva version, AAA issues it as a physical booklet with no digital option, and an in-branch visit is the only way to get it inside a week.'],
      ['This week', '<strong>The rental car at Mishima</strong> for 15–17 November — Toyota Rent a Car at the shinkansen exit, and confirm those dates directly because the branch calendar shows scattered closures. <strong>Picchio\'s musasabi tour for Monday 9 November</strong>: the season ends 30 November and these are the last slots of the year. <strong>The Hirata forge (Tue 10)</strong> via Wabunka. <strong>Mio Heki\'s kintsugi (Fri 20)</strong>, with the real-gold option.'],
      ['Late August – early September', '<strong>Kikunoi Honten for Thursday 19 November</strong> — phone or email only, or through the Mitsui concierge. <strong>L\'Effervescence for Tuesday 10 November</strong> via Pocket Concierge; the only night of the Tokyo block it opens. <strong>Kodaiji Jugyuan for Saturday 21 November.</strong> <strong>FORNI for Sunday 22 at 11:30</strong>, the last lunch. And <strong>the Mitsui private onsen</strong> for the 19th or the 21st, by phone, 48-hour cancellation.'],
      ['Phone calls that unblock a day', '<strong>Niji-no-Sato, 0558-72-7111</strong> — is it open on Tuesday 17 November, and do the 2026 light-up dates again start around the 15th? <strong>Shuzenji Washi, 050-3699-4284</strong> — which weekdays does the English session run in November? <strong>Vieni KANDA, 0558-73-2500</strong> — can they serve a coeliac given the building\'s history? Each of these decides part of a day.'],
      ['Early October — and one hard deadline', '<strong>14 October is when ¥1,330,000 stops being refundable at the Ritz-Carlton.</strong> Decide by the 7th, with a week of slack, whether four nights at the lake is still right. Also: <strong>Rurikoin</strong>, whose 2026 season runs 1 October – 13 December with reservation required through the peak window; the <strong>gluten-free brief</strong> to every remaining kitchen; and the <strong>takkyubin</strong> plan, arranged at check-in in Nikko on the 11th for collection on the 13th.'],
    ],
  },
};
